#!/usr/bin/env python3
"""Build TMLR LaTeX from the manuscript, historical counts, and saved coverage results."""

import argparse
import json
from pathlib import Path
import subprocess
import sys


ACADEMIC = Path(__file__).resolve().parents[1]
SOURCE = ACADEMIC / "manuscript.md"
GENERATED = ACADEMIC / "generated"
COVERAGE = ACADEMIC.parent / "studies/episodic-v3/results/main/analysis.json"
MISC3_AUDIT = ACADEMIC / "investigations/misc3-episodic-audit.json"
SUPPORT_AUDIT = ACADEMIC / "support-study-audit.json"
EPISODIC_AUDIT = ACADEMIC / "episodic-study-audit.json"


def tex_escape(value):
    replacements = {"\\": r"\textbackslash{}", "_": r"\_", "&": r"\&",
                    "%": r"\%", "#": r"\#", "$": r"\$", "{": r"\{",
                    "}": r"\}", "~": r"\textasciitilde{}", "^": r"\textasciicircum{}"}
    return "".join(replacements.get(c, c) for c in str(value))


def code(value):
    return r"\texttt{" + tex_escape(value) + "}"


def write_table(filename, headers, rows, spec, caption, label, keep_together=False, output_dir=None):
    heading = " & ".join(headers) + r" \\" + "\n"
    content = (
        "% Generated by tools/convert_manuscript.py; do not edit by hand.\n"
        "\\begingroup\n\\small\n"
        "\\begin{longtable}{" + spec + "}\n"
        "\\caption{" + caption + "}\\label{" + label + "}\\\\\n"
        "\\toprule\n" + heading + "\\midrule\n\\endfirsthead\n"
        "\\toprule\n" + heading + "\\midrule\n\\endhead\n"
        "\\bottomrule\n\\endfoot\n"
        + "".join(" & ".join(row) + r" \\" + "\n" for row in rows)
        + "\\end{longtable}\n\\endgroup\n")
    if keep_together:
        content = (
            "% Generated by tools/convert_manuscript.py; do not edit by hand.\n"
            "\\begin{table}[!htbp]\n\\centering\n\\small\n"
            "\\caption{" + caption + "}\\label{" + label + "}\n"
            "\\begin{tabular}{" + spec + "}\n\\toprule\n" + heading + "\\midrule\n"
            + "".join(" & ".join(row) + r" \\" + "\n" for row in rows)
            + "\\bottomrule\n\\end{tabular}\n\\end{table}\n")
    (Path(output_dir) if output_dir is not None else GENERATED).joinpath(filename).write_text(content)


def coverage_rows(analysis):
    rows = []
    for result in analysis["results"]:
        construction = result["construction"]
        a, b = (result["definitions"][d]["validation"] for d in ("best_a", "best_b"))
        if a.get("N") != b.get("N"):
            raise ValueError("Answer-population denominators differ")
        freezes = [(construction["frozen"][d] or {}).get("at_episode")
                   for d in ("best_a", "best_b")]
        passed = ",".join(d for d, v in (("A", a), ("B", b)) if v["coverage_claim"])
        label = (passed or "none") if construction["validation_eligible"] else "not tested"
        values = [construction["episodes"], *freezes, a.get("N"),
                  a.get("outside_occurrences"), b.get("outside_occurrences")]
        rows.append([code(result["problem"]),
                     *("--" if v is None else f"{v:,}" for v in values), label])
    return rows


def misc3_rows(audit):
    columns = ("frozen_a", "frozen_b", "validation_best_a", "validation_best_b",
               "port_best_a", "port_best_b")
    return [[code(row["answer"]), *(str(row[column]) for column in columns)]
            for row in audit["answer_table"]]


def single_check_rows(audit):
    metrics = (("Observations", "runs"), ("100-run checks", "batches"),
               ("Outside draws (including errors)", "novel_draws"),
               ("Checks with outside draws", "novel_batches"),
               ("Checks missing a p50 member", "missing_batches"),
               ("Engine-error observations", "engine_error_runs"),
               ("Frequency rejections at $0.05/19$", "frequency_rejections_19_input_adjusted"))
    return [[label, *(f'{audit["comparisons"][p][key]:,}' for p in ("validation", "port"))]
            for label, key in metrics]


def episodic_port_rows(audit):
    rows = []
    for r in audit["results"]:
        a, b = (r["definitions"][d] for d in ("best_a", "best_b"))
        if a["port_N"] != b["port_N"]:
            raise ValueError("Port answer-population denominators differ")
        passed = ",".join(label for label, d in (("A", a), ("B", b)) if d["coverage_qualified"])
        status = (passed or "none") if r["validation_eligible"] else "not tested"
        values = (a["port_N"], r["port"]["answerless_episodes"], r["port"]["capped_runs"],
                  a["outside_occurrences"], b["outside_occurrences"])
        rows.append([code(r["problem"]), *("--" if v is None else f"{v:,}" for v in values), status])
    return rows


def episodic_frequency_rows(audit):
    rows = []
    for r in audit["capped_frequency_comparisons"]:
        gap = r["largest_gap"]
        rows.append([code(r["problem"]), "A" if r["definition"] == "best_a" else "B",
                     f'{r["reference_N"]:,}', f'{r["empirical_tv"]:.4f}', code(gap["answer"]),
                     f'{gap["reference_fraction"]:.4f}', f'{gap["port_fraction"]:.4f}'])
    return rows


def generate_tables(audit, episode_audit, coverage, misc3, support, episodic):
    GENERATED.mkdir(exist_ok=True)
    rows = []
    for row in audit["results"]:
        rows.append([code(row["problem"]), f'{row["N"]:,}', str(row["distinct"]),
                     str(row["f1"]), f'{row["missing_mass_estimate"]:.8f}',
                     tex_escape(row["stop_reason"]), str(len(row["p50"]))])
    write_table("reference-table.tex",
                ["Input", "$N_x$", "$|S_x|$", "$f_{1,x}$", "$f_{1,x}/N_x$", "Stored reason", "$|H_x|$"],
                rows, "@{}lrrrrlr@{}",
                "Archived reference counts. Stopping labels describe the heuristic, not certified completeness.",
                "tab:reference")
    rows = []
    labels = ["CPU before repairs", "CPU after repairs", "Archived MLX check"]
    for label, row in zip(labels, audit["saved_cycles"]):
        rows.append([label, str(row["novel_problem_outcome_pairs"]),
                     str(row["missing_head_members"])])
    write_table("cycle-table.tex", ["Archived cycle", "Novel pairs", "Missing head members"],
                rows, "@{}lrr@{}", "Observed flags, not estimated error rates. All cycles reuse the same seed block.",
                "tab:cycles")
    metrics = [
        ("Check episodes", "episodes"),
        ("Within-episode runs", "runs"),
        ("Stored novel endpoint pairs", "stored_novel_pairs"),
        ("Episodes with stored novel endpoint", "stored_novel_episodes"),
        ("Missing stored head members", "missing_head_members"),
        ("Episodes never answering", "episodes_never_answering"),
        ("Capped within-episode runs", "capped_runs"),
        ("Episodes with any capped run", "episodes_with_cap"),
        ("Episodes ending in a capped run", "episodes_last_run_capped"),
    ]
    rows = [[label, *[f'{cycle["totals"][key]:,}' for cycle in episode_audit["cycles"]]]
            for label, key in metrics]
    write_table("episode-table.tex", ["Metric", "CPU before", "CPU after", "Archived MLX"],
                rows, "@{}lrrr@{}",
                "Archived eight-run episodes. Novelty labels come from stored flags; "
                "the historical episodic reference is unavailable for independent recomputation.",
                "tab:episodes")
    reference = json.loads((ACADEMIC / "data/reference-single-runs.json").read_text())
    cycle = json.loads((ACADEMIC / "data/vs-metacat.json").read_text())
    checks = {row["problem"]: row for row in cycle["single"]}
    rows = []
    for row in reference["results"]:
        shared = [answer for answer, count in sorted(row["states"].items(), key=lambda item: (-item[1], item[0]))
                  if answer not in ("*NONE*", "*CAP*")
                  and checks[row["name"]]["produced"].get(answer, 0) > 0][:3]
        rows.append([code(row["name"]), *map(code, row["problem"][1:]),
                     ", ".join(map(code, shared))])
    write_table("input-table.tex", ["Input", "Initial", "Modified", "Target", "Shared examples"],
                rows, "@{}lllll@{}", "Benchmark inputs and observed shared answers; examples are not correctness labels.",
                "tab:inputs")
    write_table("episodic-coverage-table.tex",
                ["Input", "Build $E$", "Freeze A", "Freeze B", "$N_v$", "Miss A", "Miss B", "Pass"],
                coverage_rows(coverage), "@{}lrrrrrrl@{}",
                "Episodic frozen-oracle coverage. $E$ counts construction episodes; "
                "$N_v$ counts answered validation episodes. A and B denote the native quality "
                "and conceptual-preference populations. Pass lists definitions meeting the 0.01 "
                "coverage target with 95\\% simultaneous confidence across all 38 populations. "
                "Dashes denote an unmet freeze or uncollected validation, not zero misses.",
                "tab:episodic-coverage", keep_together=True)
    write_table("episodic-port-table.tex",
                ["Input", "$N_p$", "No answer", "Cap runs", "Outside A", "Outside B", "Ref. pass"],
                episodic_port_rows(episodic), "@{}lrrrrrl@{}",
                "Port results for all 19 inputs, each assigned 100 eight-run episodes. "
                "$N_p$ counts answered complete episodes; No answer counts entirely answerless episodes; "
                "Cap runs counts inner runs reaching the codelet limit (out of 800). Outside counts "
                "refer to independently frozen supports. A dash means no frozen support, not zero "
                "outside winners. Ref. pass repeats the independently validated reference populations; "
                "it is not a port pass/fail verdict.", "tab:episodic-port", keep_together=True)
    fields = ("attempted_runs", "answer_runs", "answerless_runs", "capped_runs", "error_runs")
    labels = {"construction": "Construction", "validation": "Validation", "port": "Port"}
    rows = [[labels[p], *(f'{episodic["totals"][p][k]:,}' for k in fields)] for p in labels]
    write_table("episodic-accounting-table.tex", ["Phase", "Attempted", "Answered", "No answer", "Capped", "Error"],
                rows, "@{}lrrrrr@{}", "Episodic inner-run counts, including the inherited pilot. "
                "The four disjoint outcome columns sum to Attempted; No answer excludes caps and errors.",
                "tab:episodic-accounting", keep_together=True)
    write_table("episodic-capped-frequency-table.tex",
                ["Input", "Set", "$N_R$", "TV", "Largest-gap answer", "Ref. share", "Port share"],
                episodic_frequency_rows(episodic), "@{}llrrlrr@{}",
                "Descriptive frequency comparisons for all five construction-limited inputs, using "
                "complete construction samples and 100 port episodes. Both native populations are shown; "
                "shares and empirical TV are rounded to four decimals. No coverage guarantees apply.",
                "tab:episodic-capped")
    write_table("misc3-frequency-table.tex",
                ["Answer", "Freeze A", "Freeze B", "Ref. A", "Ref. B", "Port A", "Port B"],
                misc3_rows(misc3), "@{}lrrrrrr@{}",
                "Complete \\texttt{misc3} selected-answer frequencies. Freeze A and B use "
                "11 and seven construction episodes, respectively; reference validation uses "
                "1,000 episodes and the port check uses 100. Only "
                "\\texttt{kji}, \\texttt{kkjjii}, and \\texttt{kkkjjjiii} belong to the frozen supports.",
                "tab:misc3-frequencies")
    write_table("single-check-table.tex", ["Measure", "Reference validation", "Port"],
                single_check_rows(support), "@{}lrr@{}",
                "Versioned fresh-memory checks against 20,000 frozen construction runs per input. "
                "Counts pool 19 inputs for accounting, not to estimate a common outcome law. "
                "Errors are included in outside draws and also reported separately.",
                "tab:single-checks", keep_together=True)
    rows = [[code(r["problem"]), code(r["answer"]), str(r["port_count"]), str(r["validation_count"])]
            for r in support["port_novelty"]]
    write_table("single-novelty-table.tex", ["Input", "Outcome", "Port draws", "Held-out reference draws"],
                rows, "@{}llrr@{}", "All five flagged port input--outcome pairs. "
                "Held-out matches do not enlarge the frozen reference or remove recorded flags.",
                "tab:single-novelty", keep_together=True)
    fields = ("states", "validation_novel", "validation_errors", "port_novel", "port_errors",
              "port_flag_batches", "port_frequency_rejections")
    rows = [[code(r["problem"]), *(str(r[k]) for k in fields)] for r in support["per_input"]]
    write_table("single-input-table.tex",
                ["Input", "States", "Ref. new", "Ref. err.", "Port new", "Port err.", "Flag", "Freq."],
                rows, "@{}lrrrrrrr@{}", "Versioned single-run results. States counts outcomes in "
                "20,000 construction runs. Reference validation uses 30,000 runs per input and "
                "the port 1,000; errors are included in new draws. Flag counts port 100-run "
                "checks with an outside draw or absent p50 member, and Freq. counts frequency "
                "rejections at $0.05/19$, both out of ten checks per input.", "tab:single-inputs")
    names = {"fixed-1000": "Fixed 1,000/input", "fixed-5000": "Fixed 5,000/input",
             "fixed-10000": "Fixed 10,000/input", "fixed-20000": "Fixed 20,000/input",
             "singleton": "Singleton heuristic", "no-discovery": "No-discovery heuristic"}
    rows = [[names[r["model"]], f'{r["construction_runs"]:,}', str(r["validation_novel"]),
             str(r["port_novel"]), "--" if r["rule_fired_inputs"] is None else str(r["rule_fired_inputs"])]
            for r in support["prefixes"]]
    write_table("single-prefix-table.tex", ["Construction rule", "Build runs", "Ref. new", "Port new", "Fired"],
                rows, "@{}lrrrr@{}", "Shared validation and port observations under ordered-prefix "
                "construction. Fired counts triggering inputs (out of 19); untriggered rules "
                "retain 20,000 runs. Construction budgets differ.",
                "tab:single-prefixes")


def convert_source(pandoc, source, output):
    source, output = Path(source).resolve(), Path(output).resolve()
    if output.parent != ACADEMIC or output.suffix != ".tex":
        raise ValueError("LaTeX output must be a .tex file in academic")
    if source.suffix != ".md" or not source.is_file():
        raise ValueError("Manuscript source must be an existing Markdown file")
    subprocess.run([
        pandoc, str(source), "--from=markdown+raw_tex", "--to=latex",
        "--standalone", "--natbib", "--wrap=auto", "--columns=90",
        "--syntax-highlighting=none", "--template=tools/tmlr-template.tex",
        "--output=" + str(output),
    ], cwd=ACADEMIC, check=True)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--pandoc", default="pandoc")
    parser.add_argument("--source", type=Path, default=SOURCE,
                        help="Markdown source; relative paths are within academic")
    parser.add_argument("--output", type=Path, default=ACADEMIC / "support-set-oracles-tmlr.tex",
                        help="LaTeX output; relative paths are within academic")
    args = parser.parse_args()
    subprocess.run([sys.executable, str(ACADEMIC / "tools/audit_numbers.py")],
                   check=True, capture_output=True, text=True)
    audit = json.loads((ACADEMIC / "number-audit.json").read_text())
    subprocess.run([sys.executable, str(ACADEMIC / "tools/audit_episodes.py")],
                   check=True, capture_output=True, text=True)
    episode_audit = json.loads((ACADEMIC / "episode-audit.json").read_text())
    subprocess.run([sys.executable, str(ACADEMIC / "tools/investigate_misc3.py"),
                    "--output", str(MISC3_AUDIT)], check=True, capture_output=True, text=True)
    subprocess.run([sys.executable, str(ACADEMIC / "tools/audit_support_study.py")],
                   check=True, capture_output=True, text=True)
    subprocess.run([sys.executable, str(ACADEMIC / "tools/audit_episodic_study.py")],
                   check=True, capture_output=True, text=True)
    generate_tables(audit, episode_audit, json.loads(COVERAGE.read_text()),
                    json.loads(MISC3_AUDIT.read_text()), json.loads(SUPPORT_AUDIT.read_text()),
                    json.loads(EPISODIC_AUDIT.read_text()))
    source = args.source if args.source.is_absolute() else ACADEMIC / args.source
    output = args.output if args.output.is_absolute() else ACADEMIC / args.output
    convert_source(args.pandoc, source, output)
    print(f"Generated {output.name} and thirteen tables from {source.name} and saved data.")


if __name__ == "__main__":
    main()
