#!/usr/bin/env python3
"""Build TMLR LaTeX from manuscript.md and the bundled historical counts."""

import argparse
import json
from pathlib import Path
import subprocess
import sys


ACADEMIC = Path(__file__).resolve().parents[1]
SOURCE = ACADEMIC / "manuscript.md"
GENERATED = ACADEMIC / "generated"


def tex_escape(value):
    replacements = {"\\": r"\textbackslash{}", "_": r"\_", "&": r"\&",
                    "%": r"\%", "#": r"\#", "$": r"\$", "{": r"\{",
                    "}": r"\}", "~": r"\textasciitilde{}", "^": r"\textasciicircum{}"}
    return "".join(replacements.get(c, c) for c in str(value))


def code(value):
    return r"\texttt{" + tex_escape(value) + "}"


def write_table(filename, headers, rows, spec, caption, label):
    heading = " & ".join(headers) + r" \\" + "\n"
    content = (
        "% Generated by tools/convert_manuscript.py; do not edit by hand.\n"
        "\\begingroup\n\\small\n"
        "\\begin{longtable}{" + spec + "}\n"
        "\\caption{" + caption + "}\\label{" + label + "}\\\\\n"
        "\\toprule\n" + heading + "\\midrule\n\\endfirsthead\n"
        "\\toprule\n" + heading + "\\midrule\n\\endhead\n"
        "\\bottomrule\n\\endfoot\n"
        + "".join(" & ".join(row) + r" \\" + "\n" for row in rows)
        + "\\end{longtable}\n\\endgroup\n")
    (GENERATED / filename).write_text(content)


def generate_tables(audit, episode_audit):
    GENERATED.mkdir(exist_ok=True)
    rows = []
    for row in audit["results"]:
        rows.append([code(row["problem"]), f'{row["N"]:,}', str(row["distinct"]),
                     str(row["f1"]), f'{row["missing_mass_estimate"]:.8f}',
                     tex_escape(row["stop_reason"]), str(len(row["p50"]))])
    write_table("reference-table.tex",
                ["Input", "$N_x$", "$|S_x|$", "$f_{1,x}$", "$f_{1,x}/N_x$", "Stored reason", "$|H_x|$"],
                rows, "@{}lrrrrlr@{}",
                "Archived reference counts. Stopping labels describe the heuristic, not certified completeness.",
                "tab:reference")
    rows = []
    labels = ["CPU before repairs", "CPU after repairs", "Archived MLX check"]
    for label, row in zip(labels, audit["saved_cycles"]):
        rows.append([label, str(row["novel_problem_outcome_pairs"]),
                     str(row["missing_head_members"])])
    write_table("cycle-table.tex", ["Archived cycle", "Novel pairs", "Missing head members"],
                rows, "@{}lrr@{}", "Observed flags, not estimated error rates. All cycles reuse the same seed block.",
                "tab:cycles")
    metrics = [
        ("Check episodes", "episodes"),
        ("Within-episode runs", "runs"),
        ("Stored novel endpoint pairs", "stored_novel_pairs"),
        ("Episodes with stored novel endpoint", "stored_novel_episodes"),
        ("Missing stored head members", "missing_head_members"),
        ("Episodes never answering", "episodes_never_answering"),
        ("Capped within-episode runs", "capped_runs"),
        ("Episodes with any capped run", "episodes_with_cap"),
        ("Episodes ending in a capped run", "episodes_last_run_capped"),
    ]
    rows = [[label, *[f'{cycle["totals"][key]:,}' for cycle in episode_audit["cycles"]]]
            for label, key in metrics]
    write_table("episode-table.tex", ["Metric", "CPU before", "CPU after", "Archived MLX"],
                rows, "@{}lrrr@{}",
                "Archived eight-run episodes. Novelty labels come from stored flags; "
                "the historical episodic reference is unavailable for independent recomputation.",
                "tab:episodes")
    reference = json.loads((ACADEMIC / "data/reference-single-runs.json").read_text())
    cycle = json.loads((ACADEMIC / "data/vs-metacat.json").read_text())
    checks = {row["problem"]: row for row in cycle["single"]}
    rows = []
    for row in reference["results"]:
        shared = [answer for answer, count in sorted(row["states"].items(), key=lambda item: (-item[1], item[0]))
                  if answer not in ("*NONE*", "*CAP*")
                  and checks[row["name"]]["produced"].get(answer, 0) > 0][:3]
        rows.append([code(row["name"]), *map(code, row["problem"][1:]),
                     ", ".join(map(code, shared))])
    write_table("input-table.tex", ["Input", "Initial", "Modified", "Target", "Shared examples"],
                rows, "@{}lllll@{}", "Benchmark inputs and observed shared answers; examples are not correctness labels.",
                "tab:inputs")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--pandoc", default="pandoc")
    args = parser.parse_args()
    subprocess.run([sys.executable, str(ACADEMIC / "tools/audit_numbers.py")],
                   check=True, capture_output=True, text=True)
    audit = json.loads((ACADEMIC / "number-audit.json").read_text())
    subprocess.run([sys.executable, str(ACADEMIC / "tools/audit_episodes.py")],
                   check=True, capture_output=True, text=True)
    episode_audit = json.loads((ACADEMIC / "episode-audit.json").read_text())
    generate_tables(audit, episode_audit)
    subprocess.run([
        args.pandoc, SOURCE.name, "--from=markdown+raw_tex", "--to=latex",
        "--standalone", "--natbib", "--wrap=auto", "--columns=90",
        "--syntax-highlighting=none", "--template=tools/tmlr-template.tex",
        "--output=support-set-oracles-tmlr.tex",
    ], cwd=ACADEMIC, check=True)
    print("Generated TMLR LaTeX and four tables from manuscript.md and audited data.")


if __name__ == "__main__":
    main()
