"""Talking about answers — MetaCat's explanations and comparisons, in English.

Scheme source: ``answers.ss:310-333`` (``explain``), ``answers.ss:336-425``
(``theme-phrases``) and ``answers.ss:434-882`` (``get-answer-comparison-text``).

§4.7.4 is explicit that none of this is linguistic competence: "the program possesses
no genuine linguistic ability whatsoever; its ability to 'speak' is purely an illusion
arising from a flexible set of phrase-templates".  The templates are therefore *data*,
and in this port they live in ``seed_data/commentary_templates.json`` — every phrase in
this module comes from there, and nothing here writes English down in Python.  Editing
the seed data (or the admin UI, which edits the same row) changes what the program says.

Two facts about the shape of the output are worth stating before the code:

* **The comparison has one voice, not two.**  §4.6 footnote 16: "Turning off Eliza mode
  ... does not affect the commentary generated by the program when comparing different
  answers."  ``compare-answers`` (``answers.ss:428-431``) passes the *same* string as
  both the Eliza and the technical paragraph.  ``explain`` (``answers.ss:326-333``) does
  differ between voices, but only in its last sentence, and the two remain isomorphic —
  one paragraph either way, which is the property §4.6 stresses at pp. 183-184.
* **The prose is one paragraph.**  ``get-answer-comparison-text`` returns a single
  ``string-append``.  This module keeps its seven segments (the opening contrast, the two
  unique-theme sentences, the rule difference, the two incoherence remarks and the
  verdict) so a UI can lay them out, and ``text`` re-joins them with the leading spaces
  the Scheme itself emits, making the joined string the paragraph MetaCat prints.
"""

from __future__ import annotations

from functools import lru_cache
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from server.engine.memory import AnswerDescription, EpisodicMemory

# A theme as this module handles it: (dimension, relation), matching the Scheme's
# ``(<slipnode> <relation>)`` theme-pattern entries.
Theme = tuple[str, str]

# The five theme dimensions ``theme-phrases`` knows how to talk about
# (``answers.ss:340-344``).  Direction is looked up nowhere: the Scheme's own comment at
# ``answers.ss:341`` says "Direction-theme should always be the same as StringPos-theme",
# and the String-Position phrase carries the direction wording for both.
STRING_POSITION = "plato-string-position-category"
ALPHABETIC_POSITION = "plato-alphabetic-position-category"
GROUP_CATEGORY = "plato-group-category"
BOND_FACET = "plato-bond-facet"
DIRECTION = "plato-direction-category"

#: Order of the verdict criteria when the seed data does not supply one.  It is the
#: order of the ``cond`` at ``answers.ss:824-882``, and the seed data's
#: ``comparison_judgment_priority`` says the same thing.
DEFAULT_JUDGMENT_PRIORITY = (
    "both_incoherent",
    "one_incoherent_other_not",
    "fewer_unjustified_themes",
    "more_abstract_rule",
    "richer_set_of_ideas",
    "neither_better",
)


# ---------------------------------------------------------------------------
# Template plumbing
# ---------------------------------------------------------------------------


def _fill(template: str, **values: Any) -> str:
    """Substitute ``{name}`` placeholders, leaving unknown ones alone.

    The templates are user-editable through the admin UI, so substitution is tolerant:
    a brace this call has no value for stays in the text and the rest of the phrase
    still renders.
    """
    text = template
    for key, value in values.items():
        text = text.replace("{" + key + "}", "" if value is None else str(value))
    return text


def resolve_templates(templates: dict[str, Any] | None) -> dict[str, Any]:
    """Whatever the caller supplied, or the seed data if it supplied nothing.

    Served requests pass ``meta.commentary_templates``, which came from Postgres, so an
    admin edit takes effect on the next comparison.  ``None`` is for callers with no
    ``MetadataProvider``.
    """
    if templates:
        return templates
    from server.engine.metadata import default_commentary_templates

    return default_commentary_templates()


def _section(templates: dict[str, Any], *path: str) -> Any:
    """Walk into the template tree, returning ``{}`` for anything absent."""
    node: Any = templates or {}
    for key in path:
        if not isinstance(node, dict):
            return {}
        node = node.get(key, {})
    return node


def _text(templates: dict[str, Any], *path: str) -> str:
    value = _section(templates, *path)
    return value if isinstance(value, str) else ""


def punctuate_with_commas(conj: str, parts: list[str]) -> str:
    """Scheme: ``punctuate-with-commas`` (``answers.ss:267-276``).

    The comma stands before the conjunction even in the two-item case: "a, and b".
    """
    parts = [p for p in parts if p]
    if not parts:
        return ""
    if len(parts) == 1:
        return parts[0]
    if len(parts) == 2:
        return f"{parts[0]}, {conj} {parts[1]}"
    return "".join(f"{p}, " for p in parts[:-1]) + f"{conj} {parts[-1]}"


# ---------------------------------------------------------------------------
# Themes on an answer description
# ---------------------------------------------------------------------------


def themes_of(answer: AnswerDescription) -> list[Theme]:
    return list(answer.themes.items())


def unjustified_of(answer: AnswerDescription) -> list[Theme]:
    return list(answer.unjustified_themes.items())


def all_themes_of(answer: AnswerDescription) -> list[Theme]:
    """``(append (get-themes) (get-unjustified-themes))`` — ``answers.ss:456-464``.

    The two patterns are separate dicts keyed by dimension, so an entry can occur in
    both; each distinct ``(dimension, relation)`` pair contributes one theme.  The
    length of this list is what "a richer set of ideas" is measured on
    (``answers.ss:876-881``).
    """
    justified = themes_of(answer)
    return justified + [t for t in unjustified_of(answer) if t not in justified]


def _lookup(dimension: str, themes: list[Theme]) -> Theme | None:
    """``assq`` over a theme list: the *first* entry for the dimension wins."""
    for theme in themes:
        if theme[0] == dimension:
            return theme
    return None


def snag_explanation_for(
    answer: AnswerDescription,
    memory: EpisodicMemory | None,
    templates: dict[str, Any],
) -> str:
    """Scheme: ``get-snag-explanation`` (``answers.ss:302-307``).

    The sentence is rebuilt from what a ``SnagDescription`` stores — the rule and the
    target string — through ``caveat_templates.snag_explanation``, the same template the
    snag commentary uses, so the caveat quotes the wording the user saw when the snag
    happened.
    """
    snag = memory.get_equivalent_snag(answer) if memory is not None else None
    if snag is None:
        return ""
    return _fill(
        _text(templates, "caveat_templates", "snag_explanation"),
        rule=snag.description,
        target=snag.problem[2] if len(snag.problem) > 2 else "",
    )


def snag_justified_themes(
    answer: AnswerDescription, memory: EpisodicMemory | None
) -> list[Theme]:
    """Scheme: ``get-snag-justified-themes`` (``answers.ss:285-299``).

    §4.7.3: an unjustified theme is reclassified as snag-justified when the program has
    hit a snag on the very same strings and rule, because then "the differences between
    the themes involved in the snag and the themes involved in the answer provide a
    strong clue as to how ... the snag is avoided".  So the themes that count are the
    answer's themes *minus the snag's own* — the ones the snag episode did not have —
    intersected with the unjustified ones.
    """
    if memory is None:
        return []
    snag = memory.get_equivalent_snag(answer)
    if snag is None:
        return []
    snag_themes = list((snag.theme_pattern or {}).items())
    unjustified = unjustified_of(answer)
    avoiding = [t for t in all_themes_of(answer) if t not in snag_themes]
    return [t for t in avoiding if t in unjustified]


# ---------------------------------------------------------------------------
# theme-phrases  (answers.ss:336-425)
# ---------------------------------------------------------------------------


def theme_phrases(
    templates: dict[str, Any],
    *,
    prep: str,
    conj: str,
    ending: str,
    themes: list[Theme],
    snag_justified_themes: list[Theme],
    unjustified_themes: list[Theme],
    initial: str | None,
    target: str | None,
    snag_explanation: str = "",
    add_caveats: bool = False,
    the_strings: bool = False,
    two_strings: str | None = None,
) -> str:
    """Describe a set of themes as one English clause.

    A direct port of ``theme-phrases`` (``answers.ss:336-425``), including its ordering:
    String-Position (carrying Group-Category and direction), Group-Category on its own,
    Bond-Facet, Alphabetic-Position — joined by ``punctuate-with-commas``.

    The dissertation walks through exactly this function at §4.7.4 pp. 194-195, where
    slots 1 and 2 of "⟨1⟩ see⟨2⟩ ⟨3⟩ as ⟨4⟩ ⟨5⟩ ⟨6⟩" are the ``prep`` and ``ending``
    arguments that make "on seeing" or "of seeing" or "to see" as the context demands.
    """
    tpl = _section(templates, "theme_phrase_templates")
    all_themes = list(themes) + list(unjustified_themes)

    if two_strings is not None:
        strings = _fill(_text(tpl, "strings", "two_strings"), two_strings=two_strings)
    else:
        strings = _fill(
            _text(tpl, "strings", "pair"), initial=initial, target=target
        )
    the_strings_phrase = _text(tpl, "strings", "the_strings")

    caveats = _section(templates, "caveat_templates")

    def caveat(theme: Theme) -> str:
        if not add_caveats:
            return ""
        if theme in unjustified_themes:
            return _text(templates, "caveat_templates", "unjustified")
        if theme in snag_justified_themes:
            return _fill(
                caveats.get("snag_justified", ""),
                snag_explanation=snag_explanation,
            )
        return ""

    string_position = _lookup(STRING_POSITION, all_themes)
    group_category = _lookup(GROUP_CATEGORY, all_themes)
    bond_facet = _lookup(BOND_FACET, all_themes)
    alphabetic = _lookup(ALPHABETIC_POSITION, all_themes)

    # An unjustified Group-Category theme is not mentioned as a qualifier
    # (``answers.ss:366-368``): the program will not assert an idea it cannot back up.
    group_category_usable = group_category is not None and (
        group_category not in unjustified_themes
    )

    parts: list[str] = []

    if string_position is not None:
        section = _section(tpl, "string_position")
        qualifier = ""
        if group_category_usable:
            qualifier = _section(section, "group_qualifier").get(
                group_category[1], ""
            )
        parts.append(
            _fill(
                section.get("template", ""),
                prep=prep,
                ending=ending,
                strings=strings,
                group_qualifier=qualifier,
                direction=_section(section, "direction").get(string_position[1], ""),
                caveat=caveat(string_position),
            )
        )

    if group_category is not None and string_position is None and group_category_usable:
        section = _section(tpl, "group_category_standalone")
        parts.append(
            _fill(
                section.get("template", ""),
                prep=prep,
                ending=ending,
                strings=strings,
                group_category=_section(section, "group_category").get(
                    group_category[1], ""
                ),
                bond_facet_clause=(
                    section.get("bond_facet_clause", "")
                    if bond_facet is not None
                    else ""
                ),
                caveat=caveat(group_category),
            )
        )

    # ``answers.ss:403-406``: Bond-Facet gets its own clause unless the Group-Category
    # clause above already carried it.
    if bond_facet is not None and (
        string_position is not None or not group_category_usable
    ):
        parts.append(
            _fill(
                _text(tpl, "bond_facet", "template"),
                prep=prep,
                ending=ending,
                strings=(
                    the_strings_phrase
                    if (string_position is not None or the_strings)
                    else strings
                ),
                caveat=caveat(bond_facet),
            )
        )

    if alphabetic is not None:
        section = _section(tpl, "alphabetic_position")
        parts.append(
            _fill(
                section.get("template", ""),
                prep=prep,
                ending=ending,
                relation=_section(section, "relation").get(alphabetic[1], ""),
                strings=(
                    the_strings_phrase
                    if (string_position is not None or the_strings)
                    else strings
                ),
                caveat=caveat(alphabetic),
            )
        )

    return punctuate_with_commas(conj, parts)


# ---------------------------------------------------------------------------
# Quality and coherence phrases
# ---------------------------------------------------------------------------


def quality_phrase(quality: float, templates: dict[str, Any]) -> str:
    """Scheme: ``answer-quality-phrase`` (``answers.ss:95-105``)."""
    for entry in (templates or {}).get("answer_quality_phrases", []):
        maximum = entry.get("max_quality")
        if maximum is None or quality < maximum:
            return entry.get("phrase", "")
    return ""


def coherence_phrase(coherence: float, templates: dict[str, Any]) -> str:
    """Scheme: ``coherence-phrase`` (``answers.ss:919-926``).

    The bands fix what the argument means.  ``answer-incoherent?``
    (``answers.ss:909-916``) declares an answer incoherent once its rule is more than 25
    points more literal than its themes, which falls inside this table's "incoherent"
    band when coherence is read as *rule abstractness minus theme abstractness*.
    :func:`coherence_score` computes it that way, and ``explain`` reports the phrase
    alongside the boolean.
    """
    for entry in (templates or {}).get("coherence_phrases", []):
        maximum = entry.get("max_coherence")
        if maximum is None or coherence < maximum:
            return entry.get("phrase", "")
    return ""


def coherence_score(answer: AnswerDescription) -> float:
    """How far the answer's rule sits below its themes in abstractness.

    Negative means the dissonance §4.7.3 describes for ``dyz``: "themes based on the
    abstract concept of opposite, but ... a literal-minded interpretation of abc => abd".
    """
    return float(answer.top_rule_abstractness) - float(answer.theme_abstractness)


# ---------------------------------------------------------------------------
# Rule comparison  (answers.ss:598-620)
# ---------------------------------------------------------------------------


#: Every Slipnet node's name begins with this, and nothing else in a rule signature
#: does.  ``rule_signature`` (``server/engine/rules.py``) renders a clause as a nest of
#: plain strings, which flattens the Scheme's distinction between a *symbol* leaf (the
#: clause type ``'intrinsic``) and a *slipnode* leaf (``plato-successor``) —
#: ``traverse-rule-clauses`` treats the two completely differently, so the walk below
#: has to recover the distinction, and the prefix is what recovers it.
_CONCEPT_PREFIX = "plato-"

#: ``_descriptor_key`` collapses ``plato-group`` and the ``'string`` symbol into one
#: token, honouring the equivalence ``traverse-rule-clauses`` spells out at
#: ``justify.ss:243-244``.  For a *conceptual depth* the token still has to name a real
#: node, so it resolves back to the group.
_COLLAPSED_GROUP_TOKEN = "plato-group|string"


def _is_concept(leaf: Any) -> bool:
    """Is this leaf a Slipnet node, as opposed to one of the Scheme's bare symbols?"""
    return isinstance(leaf, str) and leaf.startswith(_CONCEPT_PREFIX)


def _is_verbatim_signature(signature: Any) -> bool:
    """Scheme: ``verbatim-rule-clause-list?`` (``justify.ss:250-253``)."""
    return (
        isinstance(signature, (list, tuple))
        and len(signature) == 1
        and isinstance(signature[0], (list, tuple))
        and len(signature[0]) > 0
        and signature[0][0] == "verbatim"
    )


def _without_empty_slots(value: Any) -> Any:
    """Drop the empty optional slots the port's clause encoding carries.

    A Scheme rule clause has no empty slots.  A change is ``(scope dimension
    descriptor)`` (``rules.ss:889-909``), and that one descriptor slot holds *either* a
    relation such as ``plato-successor`` *or* the literal node the relation was
    substituted for — "this avoids rules such as 'Change LettCtgy of object with LettCtgy
    `c` to successor' by substituting the literal descriptor (i.e., `d`) for the
    relation".  So the abstract reading of a change and the literal reading of it line up
    slot for slot, and ``traverse-rule-clauses`` compares ``plato-successor`` against
    ``plato-d`` as one concept pair — which is precisely §4.7.4's contrast between xyd's
    rule and dyz's.

    ``RuleChange`` spreads that slot across ``from_descriptor``, ``to_descriptor`` and
    ``relation`` and fills exactly one of them
    (``rules.py:_instantiate_change_template``), so ``rule_signature`` writes two
    ``None``s beside every descriptor — and they land in *different* positions for an
    abstract change than for a literal one.  Left in, they turn the Scheme's single
    concept pair into two half-empty ones; the empty slots carry no concept, so they take
    no part in a comparison the Scheme defines over concepts.
    """
    if isinstance(value, (list, tuple)):
        return [_without_empty_slots(item) for item in value if item is not None]
    return value


def _traverse(x1: Any, x2: Any, differences: list[tuple[str, str]]) -> bool:
    """Scheme: ``traverse-rule-clauses`` (``justify.ss:232-247``) under
    ``rule-clause-comparison-proc`` (``justify.ss:269-273``).

    Walks the two clause trees in lockstep.  Returns ``False`` for the Scheme's
    ``(fail)`` — a shape mismatch, or two symbols that are not the same symbol — and
    otherwise appends every pair of *concepts* the two rules disagree about.
    """
    x1_is_list = isinstance(x1, (list, tuple))
    x2_is_list = isinstance(x2, (list, tuple))
    if x1_is_list and x2_is_list:
        # ``justify.ss:237-240``: equal-length lists recur element by element; unequal
        # lengths reach ``(or (null? x1) (null? x2))`` and fail.
        if len(x1) != len(x2):
            return False
        for item1, item2 in zip(x1, x2):
            if not _traverse(item1, item2, differences):
                return False
        return True
    if x1_is_list or x2_is_list:
        # ``justify.ss:241``: a list against an atom.
        return False
    concept1, concept2 = _is_concept(x1), _is_concept(x2)
    if concept1 and concept2:
        # ``justify.ss:246``: both leaves are Slipnet nodes, so the proc decides.
        if x1 != x2:
            differences.append((x1, x2))
        return True
    if concept1 or concept2:
        # ``justify.ss:245``: a symbol against a node is a structural mismatch.
        return False
    # ``justify.ss:242``: two symbols, which have to *be* the same symbol.
    return x1 == x2


def compare_rule_signatures(
    signature_a: list | None, signature_b: list | None
) -> list[tuple[str, str]] | None:
    """Scheme: ``compare-rule-clause-lists`` (``justify.ss:256-266``), used at
    ``answers.ss:603-604`` and ``memory.ss:556-559``.

    Returns the pairs of concepts the two rules disagree about, or ``None`` when the
    clause lists cannot be aligned at all.  ``None`` is what makes MetaCat say the
    change is viewed "in a completely different way", and what sends
    ``calculate-answer-distance`` to its abstractness fallback.

    Two properties of the Scheme that a flatten-and-zip comparison loses, and that the
    reminding distance depends on:

    * **A symbol mismatch is a failure, not a difference.**  An intrinsic rule against a
      verbatim one shares no structure at all; ``traverse-rule-clauses`` fails on the
      clause-type symbols before reaching any concept.  Flattened, the clause types read
      as two more strings, the pair is dropped by the depth filter (neither names a
      Slipnet node, so both score depth 0), and two utterly unrelated rules come out
      *zero* apart.
    * **Verbatim clause lists are compared whole.**  ``compare-rule-clause-lists``
      short-circuits them to "equal or incomparable" rather than walking into the
      letters, so two different verbatim rules take the abstractness fallback instead of
      contributing a pile of same-depth letter pairs that the filter then discards.

    (The Scheme tests ``rc-list1`` twice at ``justify.ss:258-259`` where it plainly means
    ``rc-list1`` and ``rc-list2``.  The typo is inert: whenever exactly one side is
    verbatim, the walk it falls through to fails on ``verbatim`` against ``intrinsic``
    and returns ``#f`` — the same answer the short-circuit would have given.  This port
    tests both sides, which is the same function.)
    """
    if signature_a is None or signature_b is None:
        return None
    clauses_a = _without_empty_slots(signature_a)
    clauses_b = _without_empty_slots(signature_b)
    if _is_verbatim_signature(clauses_a) or _is_verbatim_signature(clauses_b):
        return [] if clauses_a == clauses_b else None
    differences: list[tuple[str, str]] = []
    if not _traverse(clauses_a, clauses_b, differences):
        return None
    return differences


def _depth_key(name: str) -> str:
    return "plato-group" if name == _COLLAPSED_GROUP_TOKEN else name


@lru_cache(maxsize=1)
def default_conceptual_depths() -> dict[str, float]:
    """Every Slipnet node's conceptual depth as it stands in ``seed_data/``.

    ``count_rule_differences`` needs depths whether or not its caller holds a
    ``MetadataProvider``: ``EpisodicMemory.distance`` is reached from
    ``find_remindings`` with no metadata in hand, and dropping the filter there would
    silently restore the very behaviour the filter exists to prevent.  Served requests
    still pass ``meta``, so an admin edit to a depth takes effect at once; this is the
    fallback, in the same spirit as ``default_commentary_templates``.
    """
    import json
    import os

    from server.engine.metadata import DEFAULT_SEED_DIR

    path = os.path.join(DEFAULT_SEED_DIR, "slipnet_nodes.json")
    try:
        with open(path) as f:
            nodes = json.load(f)
    except OSError:
        return {}
    if isinstance(nodes, dict):
        nodes = nodes.get("nodes", [])
    return {
        node["name"]: float(node.get("conceptual_depth", 0) or 0)
        for node in nodes
        if isinstance(node, dict) and "name" in node
    }


def conceptual_depth_lookup(meta: Any = None):
    """A ``name -> depth`` function, from ``meta`` when there is one and the seed data
    otherwise."""
    specs = getattr(meta, "slipnet_node_specs", None) if meta is not None else None
    if specs:

        def from_meta(name: str) -> float:
            spec = specs.get(_depth_key(name))
            return float(getattr(spec, "conceptual_depth", 0) or 0)

        return from_meta

    depths = default_conceptual_depths()
    return lambda name: depths.get(_depth_key(name), 0.0)


def count_rule_differences(
    differences: list[tuple[str, str]] | None, meta: Any = None
) -> int:
    """``num-rule-differences`` (``answers.ss:605-610``, ``memory.ss:560-565``): −1 when
    incomparable.

    Differences between two concepts of *equal conceptual depth* do not count — a rule
    that says "predecessor" where another says "successor" is a different rule, but not
    a rule pitched at a different level, and MetaCat's "the only essential difference"
    sentence is about level.  ``leftmost`` against ``rightmost`` is the canonical case:
    both sit at depth 40, so a rule that changes the leftmost letter and one that
    changes the rightmost are, on this measure, the same distance from anything.
    """
    if differences is None:
        return -1
    depth = conceptual_depth_lookup(meta)
    return sum(1 for x, y in differences if depth(x) != depth(y))


# ---------------------------------------------------------------------------
# explain  (answers.ss:310-333)
# ---------------------------------------------------------------------------


def explain_answer(
    answer: AnswerDescription,
    memory: EpisodicMemory | None = None,
    templates: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """Say what one answer rests on, and what the program thinks of it.

    Scheme: ``explain`` (``answers.ss:310-333``).  The two voices differ only in the
    closing sentence — "Personally, I think this answer is pretty mediocre." against
    "Answer quality = 71." — which is the isomorphism §4.6 describes: the same number of
    paragraphs saying the same things, with the window-dressing stripped out.
    """
    templates = resolve_templates(templates)
    section = _section(templates, "answer_explanation")
    initial, _modified, target, _answer_text = answer.problem

    snag_justified = snag_justified_themes(answer, memory)
    unjustified = [t for t in unjustified_of(answer) if t not in snag_justified]

    phrases = theme_phrases(
        templates,
        prep="on ",
        conj="and",
        ending="ing",
        themes=themes_of(answer),
        snag_justified_themes=snag_justified,
        unjustified_themes=unjustified,
        initial=initial,
        target=target,
        snag_explanation=snag_explanation_for(answer, memory, templates),
        add_caveats=True,
        the_strings=False,
    )
    explanation = _fill(section.get("template", ""), theme_phrases=phrases)
    phrase = quality_phrase(answer.quality, templates)

    eliza = explanation + _fill(
        section.get("quality_suffix_eliza", ""), quality_phrase=phrase
    )
    technical = explanation + _fill(
        section.get("quality_suffix_technical", ""),
        quality=f"{answer.quality:.0f}",
    )
    return {
        "eliza_text": eliza,
        "technical_text": technical,
        "explanation": explanation,
        "quality_phrase": phrase,
        "coherence_phrase": coherence_phrase(coherence_score(answer), templates),
        "is_coherent": answer.is_coherent,
    }


# ---------------------------------------------------------------------------
# get-answer-comparison-text  (answers.ss:434-882)
# ---------------------------------------------------------------------------


def compare_answers_text(
    answer_a: AnswerDescription,
    answer_b: AnswerDescription,
    memory: EpisodicMemory | None = None,
    templates: dict[str, Any] | None = None,
    meta: Any = None,
) -> dict[str, Any]:
    """The full comparison paragraph for two answers.

    A port of ``get-answer-comparison-text`` (``answers.ss:434-882``).  The classification
    it works from — common, differing and unique themes, unjustified and snag-justified
    themes, and the two rules — is §4.7.3's, and the phrase-templates it fills are
    §4.7.4's.  What comes out is one paragraph; the segments are returned separately only
    so a UI can break it up.
    """
    ctx = AnswerComparison(answer_a, answer_b, memory, templates, meta)
    return ctx.render()


class AnswerComparison:
    """The ``let*`` block of ``get-answer-comparison-text``, kept in one place.

    The Scheme binds some fifty intermediate values before its first ``string-append``,
    and they are interdependent: the verdict needs the theme classification, and the
    unique-theme sentences need to know which answer was mentioned first.  They are
    computed once in ``__init__`` and read by the segment methods.
    """

    def __init__(
        self,
        self_answer: AnswerDescription,
        other_answer: AnswerDescription,
        memory: EpisodicMemory | None = None,
        templates: dict[str, Any] | None = None,
        meta: Any = None,
    ) -> None:
        templates = resolve_templates(templates)
        self.templates = templates
        self.meta = meta
        self.memory = memory
        self.a = self_answer
        self.b = other_answer
        cmp_tpl = _section(templates, "comparison_templates")
        self.tpl = cmp_tpl

        self.initial1, self.modified1, self.target1, self.answer1 = self_answer.problem
        self.initial2, self.modified2, self.target2, self.answer2 = other_answer.problem

        self.problem1 = _fill(
            cmp_tpl.get("problem", ""),
            initial=self.initial1,
            modified=self.modified1,
            target=self.target1,
        )
        self.problem2 = _fill(
            cmp_tpl.get("problem", ""),
            initial=self.initial2,
            modified=self.modified2,
            target=self.target2,
        )
        self.change1 = _fill(
            cmp_tpl.get("change", ""), initial=self.initial1, modified=self.modified1
        )
        self.change2 = _fill(
            cmp_tpl.get("change", ""), initial=self.initial2, modified=self.modified2
        )
        self.full_answer1 = _fill(
            cmp_tpl.get("full_answer", ""), answer=self.answer1, problem=self.problem1
        )
        self.full_answer2 = _fill(
            cmp_tpl.get("full_answer", ""), answer=self.answer2, problem=self.problem2
        )
        # ``answers.ss:450-451``: an answer is named with its problem on first mention,
        # and by name alone once both answers belong to the same problem.
        same_problem = self.problem1 == self.problem2
        self.answer1_phrase = self.answer1 if same_problem else self.full_answer1
        self.answer2_phrase = self.answer2 if same_problem else self.full_answer2

        # ---- theme classification (answers.ss:455-543) ----
        self.all_themes1 = all_themes_of(self_answer)
        self.all_themes2 = all_themes_of(other_answer)
        self.snag_justified1 = snag_justified_themes(self_answer, memory)
        self.snag_justified2 = snag_justified_themes(other_answer, memory)
        self.unjustified1 = [
            t for t in unjustified_of(self_answer) if t not in self.snag_justified1
        ]
        self.unjustified2 = [
            t for t in unjustified_of(other_answer) if t not in self.snag_justified2
        ]
        self.all_unjustified = list(self.unjustified1)
        self.all_unjustified += [
            t for t in self.unjustified2 if t not in self.all_unjustified
        ]
        self.snag_explanation1 = snag_explanation_for(self_answer, memory, templates)
        self.snag_explanation2 = snag_explanation_for(other_answer, memory, templates)

        self.common_themes = [t for t in self.all_themes1 if t in self.all_themes2]
        common_dimensions = {d for d, _ in self.common_themes}
        dimensions1 = [d for d, _ in self.all_themes1]
        dimensions2 = {d for d, _ in self.all_themes2}
        self.differing_dimensions = [
            d
            for d in dict.fromkeys(dimensions1)
            if d in dimensions2 and d not in common_dimensions
        ]
        self.answer1_only = [t for t in self.all_themes1 if t not in self.common_themes]
        self.answer2_only = [t for t in self.all_themes2 if t not in self.common_themes]
        self.differing1 = [
            t for t in self.all_themes1 if t[0] in self.differing_dimensions
        ]
        self.differing2 = [
            t for t in self.all_themes2 if t[0] in self.differing_dimensions
        ]
        self.unique1 = [t for t in self.answer1_only if t not in self.differing1]
        self.unique2 = [t for t in self.answer2_only if t not in self.differing2]

        common_unjustified = [t for t in self.unjustified1 if t in self.unjustified2]
        self.common_a_only_unjustified = [
            t
            for t in self.unjustified1
            if t not in common_unjustified and t not in self.differing1
        ]
        self.common_b_only_unjustified = [
            t
            for t in self.unjustified2
            if t not in common_unjustified and t not in self.differing2
        ]
        self.justification_differences = bool(
            self.common_a_only_unjustified or self.common_b_only_unjustified
        )

        self.num_theme_differences = (
            len(self.differing_dimensions) + len(self.unique1) + len(self.unique2)
        )
        self.theme_differences = self.num_theme_differences != 0

        # ---- rule comparison (answers.ss:597-620) ----
        self.rule_differences = compare_rule_signatures(
            self_answer.top_rule_signature, other_answer.top_rule_signature
        )
        self.num_rule_differences = count_rule_differences(self.rule_differences, meta)
        self.rule_differences_exist = self.num_rule_differences != 0
        rule_tpl = _section(cmp_tpl, "rule_explanation")
        if self.rule_differences is None:
            self.rule_difference_phrase = rule_tpl.get(
                "phrase_completely_different", ""
            )
        else:
            delta = (
                self_answer.top_rule_abstractness - other_answer.top_rule_abstractness
            )
            if delta > 0:
                self.rule_difference_phrase = rule_tpl.get("phrase_more_abstract", "")
            elif delta < 0:
                self.rule_difference_phrase = rule_tpl.get("phrase_more_literal", "")
            else:
                self.rule_difference_phrase = rule_tpl.get(
                    "phrase_somewhat_different", ""
                )

        # ``answers.ss:621-637``: in the one branch where the second answer is named
        # first, two answers that spell the same have to swap "first" and "second".
        self.b_mentioned_first = self.theme_differences and not self.answer1_only
        self.order1 = "second" if self.b_mentioned_first else "first"
        self.order2 = "first" if self.b_mentioned_first else "second"
        same_string = self.answer1 == self.answer2
        self.same_string = same_string
        ordinal = cmp_tpl.get("answer_ordinal", "")
        self.answer1_ref = (
            _fill(ordinal, order=self.order1, answer=self.answer1)
            if same_string
            else self.answer1
        )
        self.answer2_ref = (
            _fill(ordinal, order=self.order2, answer=self.answer2)
            if same_string
            else self.answer2
        )

    # -- reusable clauses ---------------------------------------------------

    def _similarities(self, with_caveats: bool) -> str:
        """``similarities`` (``answers.ss:659-669``) — what both answers rely on."""
        section = _section(self.tpl, "no_theme_differences")
        if self.initial1 == self.initial2 and self.target1 == self.target2:
            two_strings = _fill(
                section.get("similarity_strings_same_problem", ""),
                initial=self.initial1,
                target=self.target1,
            )
        else:
            two_strings = _fill(
                section.get("similarity_strings_different_problems", ""),
                initial1=self.initial1,
                target1=self.target1,
                initial2=self.initial2,
                target2=self.target2,
            )
        return _fill(
            section.get("similarities", ""),
            theme_phrases=theme_phrases(
                self.templates,
                prep="on ",
                conj="and",
                ending="ing",
                themes=self.common_themes,
                snag_justified_themes=[],
                unjustified_themes=self.all_unjustified,
                initial=None,
                target=None,
                add_caveats=with_caveats,
                the_strings=False,
                two_strings=two_strings,
            ),
        )

    def _no_justification(self, first: bool) -> str:
        """``no-justification1`` / ``no-justification2`` (``answers.ss:549-590``)."""
        section = _section(self.tpl, "no_theme_differences")
        if first:
            themes = self.common_a_only_unjustified
            snag_justified, unjustified = self.snag_justified1, self.unjustified1
            initial, target = self.initial1, self.target1
            other_initial, other_target = self.initial2, self.target2
            other_snag_justified = self.snag_justified2
            other_snag_explanation = self.snag_explanation2
            key = "no_justification_former"
        else:
            themes = self.common_b_only_unjustified
            snag_justified, unjustified = self.snag_justified2, self.unjustified2
            initial, target = self.initial2, self.target2
            other_initial, other_target = self.initial1, self.target1
            other_snag_justified = self.snag_justified1
            other_snag_explanation = self.snag_explanation1
            key = "no_justification_latter"

        shared_with_other_snag = [t for t in themes if t in other_snag_justified]
        snag_clause = ""
        if shared_with_other_snag:
            snag_clause = _fill(
                section.get("no_justification_snag_clause", ""),
                theme_phrases=theme_phrases(
                    self.templates,
                    prep="",
                    conj="and",
                    ending="ing",
                    themes=shared_with_other_snag,
                    snag_justified_themes=[],
                    unjustified_themes=shared_with_other_snag,
                    initial=other_initial,
                    target=other_target,
                    the_strings=True,
                ),
                snag_explanation=other_snag_explanation,
            )
        return _fill(
            section.get(key, ""),
            theme_phrases=theme_phrases(
                self.templates,
                prep="to ",
                conj="or",
                ending="",
                themes=themes,
                snag_justified_themes=snag_justified,
                unjustified_themes=unjustified,
                initial=initial,
                target=target,
                the_strings=True,
            ),
            initial=other_initial,
            target=other_target,
            snag_clause=snag_clause,
        )

    def _rule_explanation(self, intro: str, subject: str) -> str:
        """``rule-explanation-template`` (``answers.ss:638-652``)."""
        section = _section(self.tpl, "rule_explanation")
        if self.same_string:
            answer1 = _fill(section.get("answer1_ordinal", ""), order=self.order1)
            answer2 = _fill(section.get("answer2_ordinal", ""), order=self.order2)
        else:
            answer1 = _fill(section.get("answer1_named", ""), answer=self.answer1)
            answer2 = _fill(section.get("answer2_named", ""), answer=self.answer2)
        change2 = (
            section.get("change2_same", "")
            if self.change1 == self.change2
            else _fill(section.get("change2_different", ""), change2=self.change2)
        )
        return _fill(
            section.get("template", ""),
            intro=intro,
            subject=subject,
            change1=self.change1,
            rule_difference_phrase=self.rule_difference_phrase,
            answer1=answer1,
            change2=change2,
            answer2=answer2,
        )

    def _answer_theme_phrases(self, first: bool, themes: list[Theme]) -> str:
        if first:
            return theme_phrases(
                self.templates,
                prep="on ",
                conj="and",
                ending="ing",
                themes=themes,
                snag_justified_themes=self.snag_justified1,
                unjustified_themes=self.unjustified1,
                initial=self.initial1,
                target=self.target1,
                snag_explanation=self.snag_explanation1,
                add_caveats=True,
            )
        return theme_phrases(
            self.templates,
            prep="on ",
            conj="and",
            ending="ing",
            themes=themes,
            snag_justified_themes=self.snag_justified2,
            unjustified_themes=self.unjustified2,
            initial=self.initial2,
            target=self.target2,
            snag_explanation=self.snag_explanation2,
            add_caveats=True,
        )

    # -- segments -----------------------------------------------------------

    def _opening(self) -> str:
        no_diff = _section(self.tpl, "no_theme_differences")
        diff = _section(self.tpl, "theme_differences")
        in_part = diff.get("in_part", "")

        if not self.theme_differences:
            if not self.rule_differences_exist and not self.justification_differences:
                if self.change1 == self.change2:
                    sameness = _fill(
                        no_diff.get("rule_sameness_same_change", ""),
                        change1=self.change1,
                    )
                else:
                    sameness = _fill(
                        no_diff.get("rule_sameness_different_change", ""),
                        change1=self.change1,
                        change2=self.change2,
                    )
                return _fill(
                    no_diff.get("essentially_same", ""),
                    answer1=self.answer1_phrase,
                    answer2=self.full_answer2,
                    similarities=self._similarities(True),
                    rule_sameness=sameness,
                )
            if not self.justification_differences:
                both = _fill(
                    self.tpl.get("both_answers", ""),
                    answer1=self.answer1_phrase,
                    answer2=self.full_answer2,
                )
                return _fill(
                    no_diff.get("rule_differences_only", ""),
                    rule_explanation=self._rule_explanation(
                        _text(self.tpl, "rule_explanation", "intro_only_essential"),
                        both,
                    ),
                    similarities=self._similarities(True),
                )
            if not self.common_a_only_unjustified:
                return _fill(
                    no_diff.get("justification_differences", ""),
                    answer1=self.answer1_phrase,
                    answer2=self.full_answer2,
                    similarities=self._similarities(False),
                    no_justification=self._no_justification(False),
                )
            if not self.common_b_only_unjustified:
                return _fill(
                    no_diff.get("justification_differences", ""),
                    answer1=self.answer1_phrase,
                    answer2=self.full_answer2,
                    similarities=self._similarities(False),
                    no_justification=self._no_justification(True),
                )
            return _fill(
                no_diff.get("justification_differences_both", ""),
                answer1=self.answer1_phrase,
                answer2=self.full_answer2,
                similarities=self._similarities(False),
                no_justification1=self._no_justification(True),
                no_justification2=self._no_justification(False),
            )

        # Theme differences.
        if not self.answer1_only:
            return _fill(
                diff.get("one_answer", ""),
                answer=self.full_answer2,
                in_part=in_part if self.common_themes else "",
                theme_phrases=self._answer_theme_phrases(False, self.answer2_only),
            )
        if not self.answer2_only:
            return _fill(
                diff.get("one_answer", ""),
                answer=self.full_answer1,
                in_part=in_part if self.common_themes else "",
                theme_phrases=self._answer_theme_phrases(True, self.answer1_only),
            )
        return _fill(
            diff.get("both_answers", ""),
            answer1=self.full_answer1,
            in_part1=in_part if self.common_themes else "",
            theme_phrases1=self._answer_theme_phrases(True, self.answer1_only),
            answer2=self.answer2_phrase,
            in_part2=in_part if self.common_themes else "",
            theme_phrases2=self._answer_theme_phrases(False, self.answer2_only),
        )

    def _unique_sentence(self, first: bool) -> str:
        """``answers.ss:736-762`` — "In xyd's case, the idea ... does not arise."."""
        section = _section(self.tpl, "unique_theme")
        if first:
            themes = self.unique1
            if not themes:
                return ""
            contrast = not self.answer1_only or not self.answer2_only
            unmentioned = not self.answer2_only
            case_answer = self.answer2_phrase if unmentioned else self.answer2_ref
            snag_justified, unjustified = self.snag_justified1, self.unjustified1
            initial, target = self.initial2, self.target2
        else:
            themes = self.unique2
            if not themes:
                return ""
            contrast = (not self.answer1_only or not self.answer2_only) and (
                not self.unique1
            )
            unmentioned = not self.answer1_only
            case_answer = self.answer1_phrase if unmentioned else self.answer1_ref
            snag_justified, unjustified = self.snag_justified2, self.unjustified2
            initial, target = self.initial1, self.target1

        case = (
            _fill(section.get("case_named", ""), answer=case_answer)
            if unmentioned
            else _fill(section.get("case_possessive", ""), answer=case_answer)
        )
        return _fill(
            section.get("template", ""),
            intro=section.get(
                "intro_contrast" if contrast else "intro_plain", ""
            ),
            case=case,
            # ``answers.ss:745`` describes the theme with "of seeing", and against the
            # *other* answer's strings — it is that answer's case being described.
            theme_phrases=theme_phrases(
                self.templates,
                prep="of ",
                conj="and",
                ending="ing",
                themes=themes,
                snag_justified_themes=snag_justified,
                unjustified_themes=unjustified,
                initial=initial,
                target=target,
            ),
        )

    def _rule_sentence(self) -> str:
        if not self.rule_differences_exist:
            return ""
        if not self.theme_differences and not self.justification_differences:
            # Already said in the opening sentence.
            return ""
        section = _section(self.tpl, "rule_explanation")
        subject = (
            _fill(section.get("subject_two_identical_answers", ""), answer=self.answer1)
            if self.same_string
            else section.get("subject_the_answers", "")
        )
        return self._rule_explanation(section.get("intro_another_key", ""), subject)

    def _incoherence(self, first: bool, after_first: bool) -> str:
        """``answers.ss:772-805`` — the "seems incoherent to me" remark."""
        section = _section(self.tpl, "incoherence")
        if first:
            answer, themes = self.answer1, self.all_themes1
            initial, target, change = self.initial1, self.target1, self.change1
            snag_justified, unjustified = self.snag_justified1, self.unjustified1
            key = "first"
        else:
            answer, themes = self.answer2, self.all_themes2
            initial, target, change = self.initial2, self.target2, self.change2
            snag_justified, unjustified = self.snag_justified2, self.unjustified2
            key = "second_after_first" if after_first else "second_alone"
        similarity = section.get(
            "similarity_plural" if len(themes) > 1 else "similarity_singular", ""
        )
        return _fill(
            section.get(key, ""),
            answer=answer,
            similarity=similarity,
            initial=initial,
            target=target,
            change=change,
            theme_phrases=theme_phrases(
                self.templates,
                prep="",
                conj="and",
                ending="ing",
                themes=themes,
                snag_justified_themes=snag_justified,
                unjustified_themes=unjustified,
                initial=initial,
                target=target,
            ),
        )

    # -- the verdict (answers.ss:806-882) -----------------------------------

    def verdict(self) -> dict[str, Any]:
        """Which answer the program prefers, in the seed data's priority order.

        The order is ``comparison_judgment_priority``, which is MetaCat's ``cond`` at
        ``answers.ss:824-882`` written down as data.  Reordering that list reorders the
        judgement — which is the point of it being data.
        """
        section = _section(self.tpl, "verdict")
        priority = (self.templates or {}).get("comparison_judgment_priority") or list(
            DEFAULT_JUDGMENT_PRIORITY
        )
        for criterion in priority:
            handler = _CRITERIA.get(criterion)
            if handler is None:
                continue
            outcome = handler(self, section)
            if outcome is not None:
                outcome["criterion"] = criterion
                return outcome
        return _neither_better(self, section, section.get("intro_all_in_all", ""))

    def _better(
        self, section: dict[str, Any], first: bool, intro: str, reason: str
    ) -> dict[str, Any]:
        answer_ref = self.answer1_ref if first else self.answer2_ref
        return {
            "text": _fill(
                section.get("better", ""),
                intro=intro,
                answer=answer_ref,
                reason=reason,
            ),
            "answer": self.answer1 if first else self.answer2,
            "answer_ref": answer_ref,
        }

    # -- assembly -----------------------------------------------------------

    def render(self) -> dict[str, Any]:
        a_incoherent = not self.a.is_coherent
        b_incoherent = not self.b.is_coherent
        verdict = self.verdict()

        segments = [
            self._opening(),
            self._unique_sentence(True),
            self._unique_sentence(False),
            self._rule_sentence(),
            self._incoherence(True, False) if a_incoherent else "",
            self._incoherence(False, a_incoherent) if b_incoherent else "",
            verdict["text"],
        ]
        text = "".join(segments)
        paragraphs = [segment.strip() for segment in segments if segment.strip()]
        return {
            "text": text,
            "paragraphs": paragraphs,
            "segments": segments,
            "verdict": verdict["text"].strip(),
            # §4.6 footnote 16: comparison commentary is identical in both voices.
            "eliza_text": text,
            "technical_text": text,
            "preferred": {
                "answer": verdict.get("answer"),
                "reason": verdict.get("criterion", ""),
            },
        }


# ---------------------------------------------------------------------------
# The verdict criteria, one function each, named as the seed data names them
# ---------------------------------------------------------------------------


def _neither_better(
    ctx: AnswerComparison, section: dict[str, Any], intro: str
) -> dict[str, Any]:
    """``neither-better`` (``answers.ss:814-823``)."""
    phrase1 = quality_phrase(ctx.a.quality, ctx.templates)
    phrase2 = quality_phrase(ctx.b.quality, ctx.templates)
    if phrase1 == phrase2:
        text = _fill(
            section.get("both_same_quality", ""), intro=intro, quality_phrase=phrase1
        )
    else:
        text = _fill(
            section.get("different_quality", ""),
            intro=intro,
            answer1=ctx.answer1_ref,
            quality1=phrase1,
            answer2=ctx.answer2_ref,
            quality2=phrase2,
        )
    return {"text": text, "answer": None, "answer_ref": None}


def _criterion_both_incoherent(
    ctx: AnswerComparison, section: dict[str, Any]
) -> dict[str, Any] | None:
    """``answers.ss:825-841``: when neither answer hangs together, prefer the one that
    hangs together *less badly* — fewer abstract themes stranded above a literal rule."""
    if ctx.a.is_coherent or ctx.b.is_coherent:
        return None
    abstractness1 = ctx.a.theme_abstractness
    abstractness2 = ctx.b.theme_abstractness
    count1, count2 = len(ctx.all_themes1), len(ctx.all_themes2)
    intro = section.get("intro_overall", "")
    if (abstractness1 < abstractness2 and count1 <= count2) or (
        count1 < count2 and abstractness1 <= abstractness2
    ):
        return ctx._better(
            section,
            True,
            intro,
            _fill(section.get("reason_less_incoherent", ""), other=ctx.answer2_ref),
        )
    if (abstractness2 < abstractness1 and count2 <= count1) or (
        count2 < count1 and abstractness2 <= abstractness1
    ):
        return ctx._better(
            section,
            False,
            intro,
            _fill(section.get("reason_less_incoherent", ""), other=ctx.answer1_ref),
        )
    return _neither_better(ctx, section, section.get("intro_all_in_all", ""))


def _criterion_one_incoherent(
    ctx: AnswerComparison, section: dict[str, Any]
) -> dict[str, Any] | None:
    """``answers.ss:842-847``: the §4.7.4 worked example — xyd beats dyz "since it is
    more coherent"."""
    intro = section.get("intro_all_in_all", "")
    reason = section.get("reason_more_coherent", "")
    if ctx.a.is_coherent and not ctx.b.is_coherent:
        return ctx._better(section, True, intro, reason)
    if ctx.b.is_coherent and not ctx.a.is_coherent:
        return ctx._better(section, False, intro, reason)
    return None


def _criterion_fewer_unjustified(
    ctx: AnswerComparison, section: dict[str, Any]
) -> dict[str, Any] | None:
    """``answers.ss:848-857``."""
    intro = section.get("intro_all_in_all", "")
    count1, count2 = len(ctx.unjustified1), len(ctx.unjustified2)
    if count1 < count2:
        key = "reason_no_unjustified" if count1 == 0 else "reason_fewer_unjustified"
        return ctx._better(section, True, intro, section.get(key, ""))
    if count2 < count1:
        key = "reason_no_unjustified" if count2 == 0 else "reason_fewer_unjustified"
        return ctx._better(section, False, intro, section.get(key, ""))
    return None


def _criterion_more_abstract_rule(
    ctx: AnswerComparison, section: dict[str, Any]
) -> dict[str, Any] | None:
    """``answers.ss:858-875``.

    Only when the answers rest on the *same* ideas: with the themes agreeing, the rule
    is the only thing left to prefer one for, and MetaCat prefers the more abstract
    reading of the top change.
    """
    if ctx.theme_differences or ctx.num_rule_differences == -1:
        return None
    intro = section.get("intro_all_in_all", "")
    abstractness1 = ctx.a.top_rule_abstractness
    abstractness2 = ctx.b.top_rule_abstractness
    if abstractness1 > abstractness2:
        reason = (
            _fill(
                section.get("reason_more_abstract_same_change", ""), change=ctx.change1
            )
            if ctx.change1 == ctx.change2
            else _fill(
                section.get("reason_more_abstract_different_change", ""),
                change1=ctx.change1,
                change2=ctx.change2,
            )
        )
        return ctx._better(section, True, intro, reason)
    if abstractness2 > abstractness1:
        reason = (
            _fill(
                section.get("reason_more_abstract_same_change", ""), change=ctx.change2
            )
            if ctx.change1 == ctx.change2
            else _fill(
                section.get("reason_more_abstract_different_change", ""),
                change1=ctx.change2,
                change2=ctx.change1,
            )
        )
        return ctx._better(section, False, intro, reason)
    return None


def _criterion_richer_ideas(
    ctx: AnswerComparison, section: dict[str, Any]
) -> dict[str, Any] | None:
    """``answers.ss:876-881``."""
    intro = section.get("intro_all_in_all", "")
    reason = section.get("reason_richer_ideas", "")
    if len(ctx.all_themes1) > len(ctx.all_themes2):
        return ctx._better(section, True, intro, reason)
    if len(ctx.all_themes2) > len(ctx.all_themes1):
        return ctx._better(section, False, intro, reason)
    return None


def _criterion_neither_better(
    ctx: AnswerComparison, section: dict[str, Any]
) -> dict[str, Any] | None:
    """``answers.ss:882`` — the fallthrough, which always applies."""
    return _neither_better(ctx, section, section.get("intro_all_in_all", ""))


_CRITERIA = {
    "both_incoherent": _criterion_both_incoherent,
    "one_incoherent_other_not": _criterion_one_incoherent,
    "fewer_unjustified_themes": _criterion_fewer_unjustified,
    "more_abstract_rule": _criterion_more_abstract_rule,
    "richer_set_of_ideas": _criterion_richer_ideas,
    "neither_better": _criterion_neither_better,
}
