"""Integration tests for the help topics single-source-of-truth system.

These tests enforce that:

1. Every help topic file is valid JSON and conforms to the expected schema.
2. Every `componentName` referenced by `PanelHelpButton` in the frontend maps
   to an existing topic_key in the (English) JSON.
3. Every `topic_key` in the generated TypeScript constants file matches the
   JSON (i.e. the generation script hasn't drifted).
4. Every topic has required fields (topic_type, topic_key, title).

The single source of truth for all help text is `seed_data/help_topics.{locale}.json`.
The backend syncs it into the DB on every startup (upsert by topic_key), the
frontend fetches from `GET /api/docs/components/{key}`, and derived artifacts
(`HELP.md`, `client/src/constants/helpTopics.ts`) are generated by
`scripts/generate_help_docs.py`.
"""
from __future__ import annotations

import json
import re
from pathlib import Path

import pytest


REPO_ROOT = Path(__file__).resolve().parent.parent.parent
SEED_DIR = REPO_ROOT / "seed_data"
CLIENT_SRC = REPO_ROOT / "client" / "src"
TS_CONSTANTS = CLIENT_SRC / "constants" / "helpTopics.ts"


def _load_topics(locale: str = "en") -> list[dict]:
    """Load the help topics file for the given locale."""
    path = SEED_DIR / f"help_topics.{locale}.json"
    if not path.exists():
        # Legacy fallback
        path = SEED_DIR / "help_topics.json"
    with path.open() as f:
        return json.load(f)


@pytest.fixture
def topics_en() -> list[dict]:
    return _load_topics("en")


# ---------------------------------------------------------------------------
# Schema validation
# ---------------------------------------------------------------------------

def test_help_topics_file_is_valid_json():
    """The JSON source of truth must be parseable."""
    topics = _load_topics("en")
    assert isinstance(topics, list)
    assert len(topics) > 0, "help_topics.en.json is empty"


def test_every_topic_has_required_fields(topics_en):
    """Every topic entry must have topic_type, topic_key, and title."""
    for t in topics_en:
        assert "topic_type" in t, f"missing topic_type in {t}"
        assert "topic_key" in t, f"missing topic_key in {t}"
        assert "title" in t, f"missing title in {t}"
        assert t["topic_type"] in ("component", "glossary"), (
            f"invalid topic_type '{t['topic_type']}' for {t['topic_key']}"
        )
        assert t["topic_key"], f"empty topic_key for topic: {t}"
        assert t["title"], f"empty title for topic_key: {t['topic_key']}"


def test_topic_keys_are_unique(topics_en):
    """Each topic_key must appear at most once."""
    keys = [t["topic_key"] for t in topics_en]
    duplicates = {k for k in keys if keys.count(k) > 1}
    assert not duplicates, f"duplicate topic_keys: {duplicates}"


def test_topic_keys_use_snake_case(topics_en):
    """Topic keys should use lowercase snake_case for consistent URL mapping."""
    snake_case = re.compile(r"^[a-z][a-z0-9_]*$")
    for t in topics_en:
        assert snake_case.match(t["topic_key"]), (
            f"topic_key '{t['topic_key']}' is not snake_case"
        )


# ---------------------------------------------------------------------------
# Frontend reference validation
# ---------------------------------------------------------------------------

def _collect_panel_help_button_refs() -> set[str]:
    """Find every `componentName="..."` usage of PanelHelpButton in the frontend.

    Returns the set of topic_keys referenced. Uses a simple regex scan since we
    don't want to parse TSX. If the codebase ever uses dynamic componentName
    (e.g. `componentName={variable}`), this scanner will miss those — but that
    is itself a convention we want to discourage in favour of static literals.
    """
    refs: set[str] = set()
    pattern = re.compile(r'componentName="([a-z][a-z0-9_]*)"')
    for path in CLIENT_SRC.rglob("*.tsx"):
        text = path.read_text()
        for match in pattern.finditer(text):
            refs.add(match.group(1))
    return refs


def test_every_frontend_component_help_ref_exists_in_json(topics_en):
    """Every componentName referenced in *.tsx must map to a component topic."""
    component_keys = {
        t["topic_key"] for t in topics_en if t["topic_type"] == "component"
    }
    refs = _collect_panel_help_button_refs()
    missing = refs - component_keys
    assert not missing, (
        f"PanelHelpButton references topic_keys not in help_topics.en.json: "
        f"{sorted(missing)}. Either add them to the JSON or fix the reference."
    )


def test_at_least_one_panel_help_ref_exists():
    """Sanity check: the scanner should find at least a few references."""
    refs = _collect_panel_help_button_refs()
    assert len(refs) >= 5, (
        f"Expected at least 5 PanelHelpButton references, found {len(refs)}. "
        f"Scanner may be broken."
    )


# ---------------------------------------------------------------------------
# Generation drift check
# ---------------------------------------------------------------------------

def test_typescript_constants_match_json(topics_en):
    """The generated TS constants must stay in sync with the JSON source."""
    assert TS_CONSTANTS.exists(), (
        f"{TS_CONSTANTS.relative_to(REPO_ROOT)} is missing. "
        f"Run: python scripts/generate_help_docs.py"
    )
    ts_text = TS_CONSTANTS.read_text()

    component_keys = sorted(
        t["topic_key"] for t in topics_en if t["topic_type"] == "component"
    )
    glossary_keys = sorted(
        t["topic_key"] for t in topics_en if t["topic_type"] == "glossary"
    )

    for key in component_keys:
        assert f"'{key}'" in ts_text, (
            f"component key '{key}' is in the JSON but missing from "
            f"{TS_CONSTANTS.name}. Run: python scripts/generate_help_docs.py"
        )
    for key in glossary_keys:
        assert f"'{key}'" in ts_text, (
            f"glossary key '{key}' is in the JSON but missing from "
            f"{TS_CONSTANTS.name}. Run: python scripts/generate_help_docs.py"
        )


def test_help_md_exists():
    """The generated HELP.md must exist for docs/CI to reference."""
    help_md = REPO_ROOT / "HELP.md"
    assert help_md.exists(), (
        "HELP.md is missing. Run: python scripts/generate_help_docs.py"
    )


# ---------------------------------------------------------------------------
# Key panel coverage
# ---------------------------------------------------------------------------

REQUIRED_COMPONENT_KEYS = {
    "problem_input",
    "run_controls",
    "workspace",
    "slipnet",
    "coderack",
    "temperature",
    "themespace",
    "trace",
    "memory",
    "commentary",
    "run_history",
    "admin",
}

# Admin action topics — each describes a button in the Admin panel. Their
# detailed user/technical descriptions live in metadata (not full_desc) so
# the AdminPanel can render them as structured bullet lists.
REQUIRED_ADMIN_ACTION_KEYS = {
    "admin_clear_memory",
    "admin_full_reset",
    "admin_regenerate_help",
}

VALID_BUTTON_VARIANTS = {"warning", "danger", "utility"}


def test_all_required_components_present(topics_en):
    """Every panel in the dashboard must have a corresponding help topic."""
    component_keys = {
        t["topic_key"] for t in topics_en if t["topic_type"] == "component"
    }
    missing = REQUIRED_COMPONENT_KEYS - component_keys
    assert not missing, (
        f"Required component help topics are missing: {sorted(missing)}"
    )


# ---------------------------------------------------------------------------
# Admin action topics (structured bullet lists in metadata)
# ---------------------------------------------------------------------------

def test_all_required_admin_actions_present(topics_en):
    """Every Admin panel button must have a corresponding help topic."""
    keys = {t["topic_key"] for t in topics_en}
    missing = REQUIRED_ADMIN_ACTION_KEYS - keys
    assert not missing, (
        f"Required admin action help topics are missing: {sorted(missing)}"
    )


def test_admin_action_topics_are_component_type(topics_en):
    """Admin actions reuse topic_type='component' (served by the same API)."""
    by_key = {t["topic_key"]: t for t in topics_en}
    for key in REQUIRED_ADMIN_ACTION_KEYS:
        assert by_key[key]["topic_type"] == "component", (
            f"{key} must be topic_type=component so the /api/docs/components/"
            f"{{key}} endpoint serves it"
        )


def test_admin_action_topics_have_structured_metadata(topics_en):
    """Admin action topics must carry structured bullet lists in metadata.

    The AdminPanel renders these inline rather than as a single full_desc
    blob, so the schema requires:
      - metadata.kind == "admin_action"
      - metadata.button_variant in {warning, danger, utility}
      - metadata.user_description is a non-empty list of strings
      - metadata.technical_description is a non-empty list of strings
    """
    by_key = {t["topic_key"]: t for t in topics_en}
    for key in REQUIRED_ADMIN_ACTION_KEYS:
        topic = by_key[key]
        meta = topic.get("metadata") or {}

        assert meta.get("kind") == "admin_action", (
            f"{key}: metadata.kind must be 'admin_action'"
        )

        variant = meta.get("button_variant")
        assert variant in VALID_BUTTON_VARIANTS, (
            f"{key}: metadata.button_variant must be one of "
            f"{sorted(VALID_BUTTON_VARIANTS)}, got {variant!r}"
        )

        user_desc = meta.get("user_description")
        assert isinstance(user_desc, list) and len(user_desc) > 0, (
            f"{key}: metadata.user_description must be a non-empty list"
        )
        for i, bullet in enumerate(user_desc):
            assert isinstance(bullet, str) and bullet.strip(), (
                f"{key}: user_description[{i}] must be a non-empty string"
            )

        tech_desc = meta.get("technical_description")
        assert isinstance(tech_desc, list) and len(tech_desc) > 0, (
            f"{key}: metadata.technical_description must be a non-empty list"
        )
        for i, bullet in enumerate(tech_desc):
            assert isinstance(bullet, str) and bullet.strip(), (
                f"{key}: technical_description[{i}] must be a non-empty string"
            )


def test_admin_action_topics_have_empty_full_desc(topics_en):
    """Admin actions use metadata for structured content; full_desc stays empty.

    This guards against maintainers accidentally duplicating the description
    into both places. If someone wants to add a narrative summary, they should
    use short_desc (which is also shown by the /api/docs/components endpoint).
    """
    by_key = {t["topic_key"]: t for t in topics_en}
    for key in REQUIRED_ADMIN_ACTION_KEYS:
        assert by_key[key].get("full_desc", "") == "", (
            f"{key}: full_desc should be empty for admin actions; use "
            f"metadata.user_description and metadata.technical_description"
        )
