;; Deterministic adapter checks against the original native commentary routine.
;; Loads the engine definitions but runs no search codelets.
(define *metacat-directory* "/metacat/")
(load "/metacat/metacat-headless.ss")
(load "/study/projections.ss")
(reset-handler (lambda () (exit 1)))
(define study-fixture-count 0)
(define (check truth label)
  (unless truth (assertion-violation 'study-fixture label))
  (set! study-fixture-count (+ study-fixture-count 1)))
(define plain (list (list plato-string-position-category plato-identity)))
(define opposite (list (list plato-string-position-category plato-opposite)))
(define richer (append plain (list (list plato-direction-category plato-identity))))
(define bond-diff (list (list plato-bond-facet diff)))

(define (fixture letters quality abstractness themes unjustified)
  (make-answer-description
    (list plato-a plato-b plato-c) (list plato-a plato-b plato-d)
    (list plato-x plato-y plato-z) letters
    '() '() '("Do not change anything") '("Do not change anything")
    abstractness abstractness 20 quality
    (cons 'vertical-bridge themes) '(top-bridge) '(bottom-bridge)
    (cons 'vertical-bridge unjustified) '()))

(define (contains? text needle)
  (let loop ((i 0))
    (and (<= (+ i (string-length needle)) (string-length text))
         (or (string=? (substring text i (+ i (string-length needle))) needle)
             (loop (+ i 1))))))

(define good (fixture (list plato-a) 70 80 plain '()))
(define bad (fixture (list plato-b) 95 20 opposite '()))
(define literal (fixture (list plato-c) 90 20 plain '()))
(define equal-ideas (fixture (list plato-b) 1 80 plain '()))
(define rich (fixture (list plato-c) 60 80 richer '()))
(define unjustified (fixture (list plato-b) 99 80 plain bond-diff))

(tell *memory* 'clear)
(check (= (study-preference good bad) -1) "coherence outranks numeric quality")
(check (contains? (get-answer-comparison-text good bad) "since it is more coherent")
       "native commentary agrees about coherence")
(check (= (study-preference good literal) -1) "comparable abstract rule preferred")
(check (contains? (get-answer-comparison-text good literal) "in a more abstract way")
       "native commentary agrees about abstraction")
(check (= (study-preference good equal-ideas) 0) "numeric quality does not force native preference")
(check (not (contains? (get-answer-comparison-text good equal-ideas) "is the better answer"))
       "native commentary leaves explicit preference unresolved")
(check (= (study-preference rich good) -1) "richer coherent ideas preferred")
(check (contains? (get-answer-comparison-text rich good) "richer set of ideas")
       "native commentary agrees about richness")
(check (= (study-preference good unjustified) -1) "unjustified ideas lose before richness")
(check (contains? (get-answer-comparison-text good unjustified) "no unjustified ideas")
       "native commentary agrees about justification")
(check (eq? (car (study-best-quality (list good bad))) bad) "quality winner differs from conceptual winner")
(check (eq? (car (study-preferred (list good bad))) good) "native conceptual winner")
(check (= (length (study-preferred (list good equal-ideas))) 2) "retain unresolved conceptual co-winners")
(check (= (study-preference bad good) 1) "reverse comparison has reversed preference")
(printf "PASS ~a deterministic native selector checks; zero search codelets\n" study-fixture-count)
(exit 0)
