;; Structured adapter for the native answers.ss:825-882 preference criteria.
;; It reads the current episode's memory; it does not alter engine state or RNG.
(define (study-themes answer)
  (append (tell answer 'get-themes) (tell answer 'get-unjustified-themes)))

(define (study-unjustified answer)
  (remove-elements (get-snag-justified-themes answer)
                   (tell answer 'get-unjustified-themes)))

(define (study-preference a b)
  (let* ((bad-a (answer-incoherent? a))
         (bad-b (answer-incoherent? b))
         (ha (average-theme-abstractness a))
         (hb (average-theme-abstractness b))
         (ta (study-themes a)) (tb (study-themes b))
         (na (length ta)) (nb (length tb))
         (ua (length (study-unjustified a)))
         (ub (length (study-unjustified b)))
         (aa (tell a 'get-top-rule-abstractness))
         (ab (tell b 'get-top-rule-abstractness))
         (common (intersect-themes ta tb))
         (same-themes (and (null? (remove-elements common ta))
                           (null? (remove-elements common tb))))
         (comparable (compare-rule-clause-lists
                       (tell a 'get-top-rule-clauses)
                       (tell b 'get-top-rule-clauses))))
    (cond
      ((and bad-a bad-b)
       (cond ((and (<= ha hb) (<= na nb) (or (< ha hb) (< na nb))) -1)
             ((and (<= hb ha) (<= nb na) (or (< hb ha) (< nb na))) 1)
             (else 0)))
      (bad-a 1)
      (bad-b -1)
      ((< ua ub) -1)
      ((> ua ub) 1)
      ((and same-themes comparable (> aa ab)) -1)
      ((and same-themes comparable (< aa ab)) 1)
      ((> na nb) -1)
      ((< na nb) 1)
      (else 0))))

(define (study-preferred answers)
  (let* ((n (length answers))
         (reach (make-vector n)))
    (do ((i 0 (+ i 1))) ((= i n))
      (vector-set! reach i (make-vector n #f)))
    (do ((i 0 (+ i 1))) ((= i n))
      (do ((j (+ i 1) (+ j 1))) ((= j n))
        (let* ((a (list-ref answers i)) (b (list-ref answers j))
               (f (study-preference a b)) (r (study-preference b a)))
          (unless (= f (- r))
            (assertion-violation 'study-projection "asymmetric native preference"))
          (cond ((= f -1) (vector-set! (vector-ref reach i) j #t))
                ((= f 1) (vector-set! (vector-ref reach j) i #t))))))
    ;; Transitive closure detects cycles without making a tournament order matter.
    (do ((k 0 (+ k 1))) ((= k n))
      (do ((i 0 (+ i 1))) ((= i n))
        (do ((j 0 (+ j 1))) ((= j n))
          (when (and (vector-ref (vector-ref reach i) k)
                     (vector-ref (vector-ref reach k) j))
            (vector-set! (vector-ref reach i) j #t)))))
    (do ((i 0 (+ i 1))) ((= i n))
      (when (vector-ref (vector-ref reach i) i)
        (assertion-violation 'study-projection "cyclic native preference")))
    (filter (lambda (a)
              (not (ormap (lambda (b) (= (study-preference b a) -1)) answers)))
            answers)))

(define (study-best-quality answers)
  (if (null? answers) '()
      (let ((best (apply max (tell-all answers 'get-quality))))
        (filter (lambda (a) (= (tell a 'get-quality) best)) answers))))

(define (study-concept-name x)
  (symbol->string (if (symbol? x) x (tell x 'get-name-symbol))))

(define (study-theme-text answer)
  (let ((parts (sort string<?
                (map (lambda (theme)
                       (string-append (study-concept-name (car theme)) "="
                                      (study-concept-name (cadr theme))))
                     (study-themes answer)))))
    (if (null? parts) ""
        (let loop ((rest (cdr parts)) (result (car parts)))
          (if (null? rest) result
              (loop (cdr rest) (string-append result ";" (car rest))))))))

(define (study-write-description port projection answer)
  (display (format "DESC\t~a\t~a\t~a\t~a\t~a\t~a\t~a\t~a\t~a\t~a"
              projection (tell answer 'get-answer-print-name)
              (tell answer 'get-quality) (tell answer 'get-temperature)
              (tell answer 'get-top-rule-abstractness)
              (average-theme-abstractness answer)
              (if (answer-incoherent? answer) 0 1)
              (length (study-unjustified answer))
              (length (study-themes answer)) (study-theme-text answer)) port)
  (write-char #\newline port))
