"""Help documentation generation.

This module holds the core generation logic for derived help artifacts:
- HELP.md -- human-readable reference
- client/src/constants/helpTopics.ts -- TypeScript key constants/unions

It is imported by:
1. `scripts/generate_help_docs.py` -- CLI wrapper (manual regeneration + `--check` mode for CI)
2. `server/main.py` lifespan -- auto-regeneration on every backend startup
3. `server/api/admin.py` -- the "Regenerate Help Documentation" admin endpoint

The single source of truth for all help text is `seed_data/help_topics.{locale}.json`.
This module never reads anything else.
"""
from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path

# Repo root is two levels up from this file: server/services/help_docs.py -> .
REPO_ROOT = Path(__file__).resolve().parent.parent.parent
SEED_DIR = REPO_ROOT / "seed_data"
HELP_MD_PATH = REPO_ROOT / "HELP.md"
TS_CONSTANTS_PATH = REPO_ROOT / "client" / "src" / "constants" / "helpTopics.ts"


@dataclass
class RegenerateResult:
    """Result of a help documentation regeneration."""
    locale: str
    topics_loaded: int
    components: int
    glossary: int
    help_md_changed: bool
    ts_constants_changed: bool
    help_md_path: str
    ts_constants_path: str

    def as_dict(self) -> dict:
        return {
            "locale": self.locale,
            "topics_loaded": self.topics_loaded,
            "components": self.components,
            "glossary": self.glossary,
            "help_md_changed": self.help_md_changed,
            "ts_constants_changed": self.ts_constants_changed,
            "help_md_path": self.help_md_path,
            "ts_constants_path": self.ts_constants_path,
        }


def load_topics(locale: str = "en") -> list[dict]:
    """Load help topics for the given locale. Falls back to legacy filename."""
    candidates = [
        SEED_DIR / f"help_topics.{locale}.json",
        SEED_DIR / "help_topics.json",
    ]
    for path in candidates:
        if path.exists():
            with path.open() as f:
                return json.load(f)
    raise FileNotFoundError(
        f"No help topics file found. Looked for: {[str(p) for p in candidates]}"
    )


def _is_admin_action(topic: dict) -> bool:
    meta = topic.get("metadata") or {}
    return meta.get("kind") == "admin_action"


def _render_topic_body(lines: list[str], t: dict) -> None:
    """Render one topic's body (short_desc, full_desc, structured bullets, related concepts)."""
    if t.get("short_desc"):
        lines.append(f"**Summary:** {t['short_desc']}")
        lines.append("")
    if t.get("full_desc"):
        lines.append(t["full_desc"].replace("\\n", "\n"))
        lines.append("")
    meta = t.get("metadata") or {}

    # Structured bullet lists used by admin action topics
    if meta.get("user_description"):
        lines.append("**What this does (user perspective):**")
        lines.append("")
        for bullet in meta["user_description"]:
            lines.append(f"- {bullet}")
        lines.append("")
    if meta.get("technical_description"):
        lines.append("**Technical details:**")
        lines.append("")
        for bullet in meta["technical_description"]:
            lines.append(f"- {bullet}")
        lines.append("")

    if meta.get("key_concepts"):
        concepts = ", ".join(f"`{c}`" for c in meta["key_concepts"])
        lines.append(f"**Related concepts:** {concepts}")
        lines.append("")


def render_markdown(topics: list[dict], locale: str) -> str:
    """Render topics as a human-readable Markdown document."""
    # Split components into "panels" (dashboard UI) and "admin actions"
    components = [t for t in topics if t["topic_type"] == "component"]
    panels = sorted(
        [t for t in components if not _is_admin_action(t)],
        key=lambda t: t["topic_key"],
    )
    actions = sorted(
        [t for t in components if _is_admin_action(t)],
        key=lambda t: t["topic_key"],
    )
    glossary = sorted(
        [t for t in topics if t["topic_type"] == "glossary"],
        key=lambda t: t["topic_key"],
    )

    lines: list[str] = []
    lines.append("# Petacat Help")
    lines.append("")
    lines.append(
        "> **Auto-generated.** Do not edit this file by hand. "
        "Edit `seed_data/help_topics.{locale}.json` "
        "and run `python scripts/generate_help_docs.py` to regenerate."
    )
    lines.append("")
    lines.append(
        f"Locale: `{locale}` — {len(topics)} topics "
        f"({len(panels)} panels, {len(actions)} admin actions, "
        f"{len(glossary)} glossary)."
    )
    lines.append("")

    # --- Dashboard panels ---
    lines.append("## Dashboard Panels")
    lines.append("")
    lines.append(
        "These help topics back the `?` buttons in each dashboard panel. "
        "The same content is served by `GET /api/docs/components/{key}` and "
        "displayed in the frontend HelpPopover."
    )
    lines.append("")
    for t in panels:
        lines.append(f"### {t['title']}")
        lines.append("")
        lines.append(f"**Topic key:** `{t['topic_key']}`  ")
        _render_topic_body(lines, t)

    # --- Admin actions ---
    if actions:
        lines.append("## Admin Actions")
        lines.append("")
        lines.append(
            "Destructive or utility operations exposed via the Admin view. "
            "These topics are also served by `GET /api/docs/components/{key}` "
            "and are fetched by `AdminPanel.tsx` on mount; the structured "
            "user- and technical-description bullets are rendered directly "
            "in the admin UI."
        )
        lines.append("")
        for t in actions:
            lines.append(f"### {t['title']}")
            lines.append("")
            lines.append(f"**Topic key:** `{t['topic_key']}`  ")
            _render_topic_body(lines, t)

    # --- Glossary ---
    lines.append("## Glossary")
    lines.append("")
    lines.append(
        "Terms used throughout the architecture. Served by "
        "`GET /api/docs/glossary` and `GET /api/docs/glossary/{term}`."
    )
    lines.append("")
    for t in glossary:
        lines.append(f"### {t['title']}")
        lines.append("")
        lines.append(f"**Topic key:** `{t['topic_key']}`  ")
        _render_topic_body(lines, t)

    return "\n".join(lines) + "\n"


def render_typescript(topics: list[dict], locale: str) -> str:
    """Render topics as a TypeScript constants file."""
    components = sorted(
        t["topic_key"] for t in topics if t["topic_type"] == "component"
    )
    glossary = sorted(
        t["topic_key"] for t in topics if t["topic_type"] == "glossary"
    )

    lines: list[str] = []
    lines.append("// -------------------------------------------------------------------")
    lines.append("// Petacat — Help topic key constants")
    lines.append("// -------------------------------------------------------------------")
    lines.append("//")
    lines.append("// AUTO-GENERATED from seed_data/help_topics.{locale}.json by")
    lines.append("// scripts/generate_help_docs.py (or the admin Regenerate Help")
    lines.append("// endpoint / backend lifespan startup). Do NOT edit by hand --")
    lines.append("// changes will be lost on the next regeneration. To add or change")
    lines.append("// help topics, edit the JSON and re-run the generator.")
    lines.append("//")
    lines.append(f"// Locale: {locale}")
    lines.append("// -------------------------------------------------------------------")
    lines.append("")
    lines.append("/** Every topic_key for topic_type='component'. */")
    lines.append("export const COMPONENT_HELP_KEYS = [")
    for k in components:
        lines.append(f"  '{k}',")
    lines.append("] as const;")
    lines.append("")
    lines.append("export type ComponentHelpKey = (typeof COMPONENT_HELP_KEYS)[number];")
    lines.append("")
    lines.append("/** Every topic_key for topic_type='glossary'. */")
    lines.append("export const GLOSSARY_HELP_KEYS = [")
    for k in glossary:
        lines.append(f"  '{k}',")
    lines.append("] as const;")
    lines.append("")
    lines.append("export type GlossaryHelpKey = (typeof GLOSSARY_HELP_KEYS)[number];")
    lines.append("")
    lines.append("/** Union of every known help topic key (component or glossary). */")
    lines.append("export type HelpTopicKey = ComponentHelpKey | GlossaryHelpKey;")
    lines.append("")

    return "\n".join(lines)


def _write_if_changed(path: Path, content: str) -> bool:
    """Write content to path only if it differs from existing. Returns True if written."""
    if path.exists() and path.read_text() == content:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    return True


def regenerate_all(locale: str = "en") -> RegenerateResult:
    """Regenerate HELP.md and the TypeScript constants file from the JSON.

    Idempotent: if the generated output matches what's already on disk, no
    writes happen. Safe to call on every backend startup.

    Raises `FileNotFoundError` if the locale JSON is missing.
    """
    topics = load_topics(locale)
    components = [t for t in topics if t["topic_type"] == "component"]
    glossary = [t for t in topics if t["topic_type"] == "glossary"]

    md = render_markdown(topics, locale)
    ts = render_typescript(topics, locale)

    md_changed = _write_if_changed(HELP_MD_PATH, md)
    ts_changed = _write_if_changed(TS_CONSTANTS_PATH, ts)

    return RegenerateResult(
        locale=locale,
        topics_loaded=len(topics),
        components=len(components),
        glossary=len(glossary),
        help_md_changed=md_changed,
        ts_constants_changed=ts_changed,
        help_md_path=str(HELP_MD_PATH.relative_to(REPO_ROOT)),
        ts_constants_path=str(TS_CONSTANTS_PATH.relative_to(REPO_ROOT)),
    )


def check_drift(locale: str = "en") -> list[str]:
    """Return a list of files that would change if regenerated. Empty if in sync."""
    topics = load_topics(locale)
    drift: list[str] = []

    for path, content in [
        (HELP_MD_PATH, render_markdown(topics, locale)),
        (TS_CONSTANTS_PATH, render_typescript(topics, locale)),
    ]:
        current = path.read_text() if path.exists() else ""
        if current != content:
            drift.append(str(path.relative_to(REPO_ROOT)))

    return drift
