(define *metacat-directory* "/metacat/")
(load "/metacat/metacat-headless.ss")
(load "/selectors/projections.ss")
(load "/study/selection.ss")
(reset-handler (lambda () (exit 1)))
(define checks 0)
(define (check truth label)
  (unless truth (assertion-violation 'pilot-fixture label))
  (set! checks (+ checks 1)))
(define (fixture letter quality abstractness . themes)
  (make-answer-description
    (list plato-a plato-b plato-c) (list plato-a plato-b plato-d)
    (list plato-x plato-y plato-z) (list letter)
    '() '() '("Do not change anything") '("Do not change anything")
    abstractness abstractness 20 quality
    (cons 'vertical-bridge
      (if (null? themes) (list (list plato-string-position-category plato-identity))
          (car themes)))
    '(top-bridge) '(bottom-bridge) '(vertical-bridge) '()))
(define earlier (fixture plato-z 80 80))
(define later (fixture plato-a 80 80))
(define higher-quality (fixture plato-b 95 80))
(define more-abstract (fixture plato-c 70 90))
(tell *memory* 'clear)
(tell *memory* 'add-answer-description earlier)
(tell *memory* 'add-answer-description later)
(check (eq? (car (tell *memory* 'get-answers)) later) "native memory is newest first")
(let ((groups (pilot-best-groups (tell *memory* 'get-answers))))
  (check (eq? (caar groups) earlier) "quality tie selects earliest, not alphabetical")
  (check (eq? (car (cadr groups)) earlier) "preference tie selects earliest")
  (check (= (length (car groups)) 2) "quality co-winner evidence retained")
  (check (= (length (cadr groups)) 2) "preference co-winner evidence retained"))
(tell *memory* 'add-answer-description higher-quality)
(let ((groups (pilot-best-groups (tell *memory* 'get-answers))))
  (check (eq? (caar groups) higher-quality) "later higher quality defeats earlier answer")
  (check (eq? (car (cadr groups)) earlier) "quality does not break conceptual tie"))
(tell *memory* 'add-answer-description more-abstract)
(let ((groups (pilot-best-groups (tell *memory* 'get-answers))))
  (check (eq? (caar groups) higher-quality) "quality winner remains separate")
  (check (eq? (car (cadr groups)) more-abstract) "later preferred answer defeats earlier one"))
(check (equal? (pilot-best-groups '()) '(() ())) "empty episode has no invented answer")
(let ((port (open-output-string)))
  (pilot-write-best port 'best_a (list earlier later))
  (check (string=? (get-output-string port) "best_a\tz\n") "compact earliest-answer serialization"))
(check (string=? (study-concept-name diff) "diff") "native diff is #f, not a slipnode")
(let ((port (open-output-string))
      (answer (fixture plato-d 80 80 (list (list plato-length diff)))))
  (check (string=? (study-theme-text answer) "plato-length=diff")
         "serialize native diff relation without calling #f")
  (study-write-description port 'quality answer)
  (check (> (string-length (get-output-string port)) 0) "full description with diff serializes"))
(printf "PASS ~a native earliest-tie checks; zero search codelets\n" checks)
(exit 0)
